onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_f11/clk
add wave -noupdate /tb_f11/cpu/mclk
add wave -noupdate -group tbl -group qbus -radix octal -childformat {{{/tb_f11/a[21]} -radix octal} {{/tb_f11/a[20]} -radix octal} {{/tb_f11/a[19]} -radix octal} {{/tb_f11/a[18]} -radix octal} {{/tb_f11/a[17]} -radix octal} {{/tb_f11/a[16]} -radix octal}} -subitemconfig {{/tb_f11/a[21]} {-height 15 -radix octal} {/tb_f11/a[20]} {-height 15 -radix octal} {/tb_f11/a[19]} {-height 15 -radix octal} {/tb_f11/a[18]} {-height 15 -radix octal} {/tb_f11/a[17]} {-height 15 -radix octal} {/tb_f11/a[16]} {-height 15 -radix octal}} /tb_f11/a
add wave -noupdate -group tbl -group qbus /tb_f11/ad_oe
add wave -noupdate -group tbl -group qbus -radix octal -childformat {{{/tb_f11/ad[15]} -radix octal} {{/tb_f11/ad[14]} -radix octal} {{/tb_f11/ad[13]} -radix octal} {{/tb_f11/ad[12]} -radix octal} {{/tb_f11/ad[11]} -radix octal} {{/tb_f11/ad[10]} -radix octal} {{/tb_f11/ad[9]} -radix octal} {{/tb_f11/ad[8]} -radix octal} {{/tb_f11/ad[7]} -radix octal} {{/tb_f11/ad[6]} -radix octal} {{/tb_f11/ad[5]} -radix octal} {{/tb_f11/ad[4]} -radix octal} {{/tb_f11/ad[3]} -radix octal} {{/tb_f11/ad[2]} -radix octal} {{/tb_f11/ad[1]} -radix octal} {{/tb_f11/ad[0]} -radix octal}} -subitemconfig {{/tb_f11/ad[15]} {-height 15 -radix octal} {/tb_f11/ad[14]} {-height 15 -radix octal} {/tb_f11/ad[13]} {-height 15 -radix octal} {/tb_f11/ad[12]} {-height 15 -radix octal} {/tb_f11/ad[11]} {-height 15 -radix octal} {/tb_f11/ad[10]} {-height 15 -radix octal} {/tb_f11/ad[9]} {-height 15 -radix octal} {/tb_f11/ad[8]} {-height 15 -radix octal} {/tb_f11/ad[7]} {-height 15 -radix octal} {/tb_f11/ad[6]} {-height 15 -radix octal} {/tb_f11/ad[5]} {-height 15 -radix octal} {/tb_f11/ad[4]} {-height 15 -radix octal} {/tb_f11/ad[3]} {-height 15 -radix octal} {/tb_f11/ad[2]} {-height 15 -radix octal} {/tb_f11/ad[1]} {-height 15 -radix octal} {/tb_f11/ad[0]} {-height 15 -radix octal}} /tb_f11/ad
add wave -noupdate -group tbl -group qbus /tb_f11/sync
add wave -noupdate -group tbl -group qbus /tb_f11/din
add wave -noupdate -group tbl -group qbus /tb_f11/dout
add wave -noupdate -group tbl -group qbus /tb_f11/xrply
add wave -noupdate -group tbl -group qbus /tb_f11/wtbt
add wave -noupdate -group tbl -group qbus /tb_f11/iako
add wave -noupdate -group tbl -group init /tb_f11/dclo
add wave -noupdate -group tbl -group init /tb_f11/aclo
add wave -noupdate -group tbl -group init /tb_f11/evnt
add wave -noupdate -group tbl -group init /tb_f11/halt
add wave -noupdate -group tbl -group init /tb_f11/virq
add wave -noupdate -group tbl -group init /tb_f11/init
add wave -noupdate -group tbl -group init /tb_f11/bsel
add wave -noupdate -group tbl -group init -radix octal -childformat {{{/tb_f11/fdin[15]} -radix octal} {{/tb_f11/fdin[14]} -radix octal} {{/tb_f11/fdin[13]} -radix octal} {{/tb_f11/fdin[12]} -radix octal} {{/tb_f11/fdin[11]} -radix octal} {{/tb_f11/fdin[10]} -radix octal} {{/tb_f11/fdin[9]} -radix octal} {{/tb_f11/fdin[8]} -radix octal} {{/tb_f11/fdin[7]} -radix octal} {{/tb_f11/fdin[6]} -radix octal} {{/tb_f11/fdin[5]} -radix octal} {{/tb_f11/fdin[4]} -radix octal} {{/tb_f11/fdin[3]} -radix octal} {{/tb_f11/fdin[2]} -radix octal}} -subitemconfig {{/tb_f11/fdin[15]} {-height 15 -radix octal} {/tb_f11/fdin[14]} {-height 15 -radix octal} {/tb_f11/fdin[13]} {-height 15 -radix octal} {/tb_f11/fdin[12]} {-height 15 -radix octal} {/tb_f11/fdin[11]} {-height 15 -radix octal} {/tb_f11/fdin[10]} {-height 15 -radix octal} {/tb_f11/fdin[9]} {-height 15 -radix octal} {/tb_f11/fdin[8]} {-height 15 -radix octal} {/tb_f11/fdin[7]} {-height 15 -radix octal} {/tb_f11/fdin[6]} {-height 15 -radix octal} {/tb_f11/fdin[5]} {-height 15 -radix octal} {/tb_f11/fdin[4]} {-height 15 -radix octal} {/tb_f11/fdin[3]} {-height 15 -radix octal} {/tb_f11/fdin[2]} {-height 15 -radix octal}} /tb_f11/fdin
add wave -noupdate -group tbl -group misc -radix octal /tb_f11/ad_mux
add wave -noupdate -group tbl -group misc -radix octal /tb_f11/ad_reg
add wave -noupdate -group tbl -group misc -radix octal /tb_f11/addr
add wave -noupdate -group tbl -group misc /tb_f11/rply
add wave -noupdate -group tbl -group misc /tb_f11/bs
add wave -noupdate -group tbl -group misc /tb_f11/umap
add wave -noupdate -group tbl -group misc /tb_f11/dmr
add wave -noupdate -group tbl -group misc /tb_f11/sack
add wave -noupdate -group tbl -group misc /tb_f11/dmgo
add wave -noupdate -group tbl -group misc /tb_f11/din_iako
add wave -noupdate -group tbl -group misc /tb_f11/din_sync
add wave -noupdate -group tbl -group misc /tb_f11/in_iako
add wave -noupdate -group tbl -group misc /tb_f11/wflg
add wave -noupdate -group tbl -group misc /tb_f11/sel_all
add wave -noupdate -group tbl -group misc /tb_f11/sel_ram
add wave -noupdate -group tbl -group misc /tb_f11/tty_tx_rdy
add wave -noupdate -group tbl -group misc /tb_f11/tty_tx_ie
add wave -noupdate -group tbl -group misc /tb_f11/tty_rx_ie
add wave -noupdate -group tbl -group misc /tb_f11/ram_read
add wave -noupdate -group tbl -group misc /tb_f11/ram_write
add wave -noupdate -group f11 -group mclk /tb_f11/cpu/mclk_clr_n
add wave -noupdate -group f11 -group mclk /tb_f11/cpu/mclk
add wave -noupdate -group f11 -group mclk /tb_f11/cpu/e33
add wave -noupdate -group f11 -group mclk /tb_f11/cpu/e65
add wave -noupdate -group f11 -group mclk /tb_f11/cpu/e98
add wave -noupdate -group f11 -group mclk /tb_f11/cpu/e130
add wave -noupdate -group f11 -group mclk /tb_f11/cpu/e195
add wave -noupdate -group f11 -group mclk /tb_f11/cpu/e163
add wave -noupdate -group f11 -group mclk /tb_f11/cpu/e293
add wave -noupdate -group f11 -group mclk /tb_f11/cpu/e423
add wave -noupdate -group f11 -group mclk -radix octal -childformat {{{/tb_f11/cpu/rclk[10]} -radix octal} {{/tb_f11/cpu/rclk[9]} -radix octal} {{/tb_f11/cpu/rclk[8]} -radix octal} {{/tb_f11/cpu/rclk[7]} -radix octal} {{/tb_f11/cpu/rclk[6]} -radix octal} {{/tb_f11/cpu/rclk[5]} -radix octal} {{/tb_f11/cpu/rclk[4]} -radix octal} {{/tb_f11/cpu/rclk[3]} -radix octal} {{/tb_f11/cpu/rclk[2]} -radix octal} {{/tb_f11/cpu/rclk[1]} -radix octal} {{/tb_f11/cpu/rclk[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/rclk[10]} {-height 15 -radix octal} {/tb_f11/cpu/rclk[9]} {-height 15 -radix octal} {/tb_f11/cpu/rclk[8]} {-height 15 -radix octal} {/tb_f11/cpu/rclk[7]} {-height 15 -radix octal} {/tb_f11/cpu/rclk[6]} {-height 15 -radix octal} {/tb_f11/cpu/rclk[5]} {-height 15 -radix octal} {/tb_f11/cpu/rclk[4]} {-height 15 -radix octal} {/tb_f11/cpu/rclk[3]} {-height 15 -radix octal} {/tb_f11/cpu/rclk[2]} {-height 15 -radix octal} {/tb_f11/cpu/rclk[1]} {-height 15 -radix octal} {/tb_f11/cpu/rclk[0]} {-height 15 -radix octal}} /tb_f11/cpu/rclk
add wave -noupdate -group f11 -group mclk -group ctrl /tb_f11/cpu/clk_stop
add wave -noupdate -group f11 -group mclk -group ctrl /tb_f11/cpu/clk_stut
add wave -noupdate -group f11 -group mclk -group ctrl /tb_f11/cpu/start_a
add wave -noupdate -group f11 -group mclk -group ctrl /tb_f11/cpu/mme_hold
add wave -noupdate -group f11 -group mclk -group ctrl /tb_f11/cpu/mme_hold0
add wave -noupdate -group f11 -group mclk -group ctrl /tb_f11/cpu/symme
add wave -noupdate -group f11 -group mclk -group ctrl /tb_f11/cpu/pre_csel
add wave -noupdate -group f11 -group mclk -group ctrl /tb_f11/cpu/mmu_str
add wave -noupdate -group f11 -group mclk -group ctrl /tb_f11/cpu/mmu_str0
add wave -noupdate -group f11 -group init /tb_f11/cpu/reset
add wave -noupdate -group f11 -group init /tb_f11/cpu/init
add wave -noupdate -group f11 -group init /tb_f11/cpu/dclo
add wave -noupdate -group f11 -group init /tb_f11/cpu/ctl_err
add wave -noupdate -group f11 -group init /tb_f11/cpu/par_err
add wave -noupdate -group f11 -group init /tb_f11/cpu/bus_err
add wave -noupdate -group f11 -group init /tb_f11/cpu/abort_n
add wave -noupdate -group f11 -group gpio /tb_f11/cpu/srun
add wave -noupdate -group f11 -group gpio /tb_f11/cpu/evnt_clr
add wave -noupdate -group f11 -group gpio /tb_f11/cpu/aclo_clr
add wave -noupdate -group f11 -group gpio /tb_f11/cpu/odt_stb
add wave -noupdate -group f11 -label virq_n /tb_f11/cpu/pin_virq_n
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/sync
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/mclk
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/ad_ena
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/ad_oe
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/ad_stb
add wave -noupdate -group f11 -group f11.qbus -radix octal -childformat {{{/tb_f11/cpu/ad_reg[15]} -radix octal} {{/tb_f11/cpu/ad_reg[14]} -radix octal} {{/tb_f11/cpu/ad_reg[13]} -radix octal} {{/tb_f11/cpu/ad_reg[12]} -radix octal} {{/tb_f11/cpu/ad_reg[11]} -radix octal} {{/tb_f11/cpu/ad_reg[10]} -radix octal} {{/tb_f11/cpu/ad_reg[9]} -radix octal} {{/tb_f11/cpu/ad_reg[8]} -radix octal} {{/tb_f11/cpu/ad_reg[7]} -radix octal} {{/tb_f11/cpu/ad_reg[6]} -radix octal} {{/tb_f11/cpu/ad_reg[5]} -radix octal} {{/tb_f11/cpu/ad_reg[4]} -radix octal} {{/tb_f11/cpu/ad_reg[3]} -radix octal} {{/tb_f11/cpu/ad_reg[2]} -radix octal} {{/tb_f11/cpu/ad_reg[1]} -radix octal} {{/tb_f11/cpu/ad_reg[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/ad_reg[15]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[14]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[13]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[12]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[11]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[10]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[9]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[8]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[7]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[6]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[5]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[4]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[3]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[2]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[1]} {-height 15 -radix octal} {/tb_f11/cpu/ad_reg[0]} {-height 15 -radix octal}} /tb_f11/cpu/ad_reg
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/bus_cyc
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/bus_disable
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/bus_ena
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/bus_init
add wave -noupdate -group f11 -group f11.qbus -radix octal /tb_f11/cpu/svc
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/svc_oe
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/ad_oe
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/doe
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/fdin_oe
add wave -noupdate -group f11 -group f11.qbus -radix octal -childformat {{{/tb_f11/cpu/fdin[15]} -radix octal} {{/tb_f11/cpu/fdin[14]} -radix octal} {{/tb_f11/cpu/fdin[13]} -radix octal} {{/tb_f11/cpu/fdin[12]} -radix octal} {{/tb_f11/cpu/fdin[11]} -radix octal} {{/tb_f11/cpu/fdin[10]} -radix octal} {{/tb_f11/cpu/fdin[9]} -radix octal} {{/tb_f11/cpu/fdin[8]} -radix octal} {{/tb_f11/cpu/fdin[7]} -radix octal} {{/tb_f11/cpu/fdin[6]} -radix octal} {{/tb_f11/cpu/fdin[5]} -radix octal} {{/tb_f11/cpu/fdin[4]} -radix octal} {{/tb_f11/cpu/fdin[3]} -radix octal} {{/tb_f11/cpu/fdin[2]} -radix octal} {{/tb_f11/cpu/fdin[1]} -radix octal} {{/tb_f11/cpu/fdin[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/fdin[15]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[14]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[13]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[12]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[11]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[10]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[9]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[8]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[7]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[6]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[5]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[4]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[3]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[2]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[1]} {-height 15 -radix octal} {/tb_f11/cpu/fdin[0]} {-height 15 -radix octal}} /tb_f11/cpu/fdin
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/out_cyc
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/adr_ena
add wave -noupdate -group f11 -group f11.qbus /tb_f11/cpu/restart_end
add wave -noupdate -group 302 /tb_f11/cpu/data/pin_clk
add wave -noupdate -group 302 -group pins -radix octal -childformat {{{/tb_f11/cpu/data/pin_ad[15]} -radix octal} {{/tb_f11/cpu/data/pin_ad[14]} -radix octal} {{/tb_f11/cpu/data/pin_ad[13]} -radix octal} {{/tb_f11/cpu/data/pin_ad[12]} -radix octal} {{/tb_f11/cpu/data/pin_ad[11]} -radix octal} {{/tb_f11/cpu/data/pin_ad[10]} -radix octal} {{/tb_f11/cpu/data/pin_ad[9]} -radix octal} {{/tb_f11/cpu/data/pin_ad[8]} -radix octal} {{/tb_f11/cpu/data/pin_ad[7]} -radix octal} {{/tb_f11/cpu/data/pin_ad[6]} -radix octal} {{/tb_f11/cpu/data/pin_ad[5]} -radix octal} {{/tb_f11/cpu/data/pin_ad[4]} -radix octal} {{/tb_f11/cpu/data/pin_ad[3]} -radix octal} {{/tb_f11/cpu/data/pin_ad[2]} -radix octal} {{/tb_f11/cpu/data/pin_ad[1]} -radix octal} {{/tb_f11/cpu/data/pin_ad[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/pin_ad[15]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[14]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[13]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[12]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[11]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[10]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[9]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[8]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[7]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[6]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[5]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[4]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[3]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[2]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[1]} {-height 15 -radix octal} {/tb_f11/cpu/data/pin_ad[0]} {-height 15 -radix octal}} /tb_f11/cpu/data/pin_ad
add wave -noupdate -group 302 -group pins /tb_f11/cpu/data/pin_bs
add wave -noupdate -group 302 -group pins /tb_f11/cpu/data/pin_ez_n
add wave -noupdate -group 302 -group pins -radix hexadecimal -childformat {{{/tb_f11/cpu/data/pin_m[15]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[14]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[13]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[12]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[11]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[10]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[9]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[8]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[7]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[6]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[5]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[4]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[3]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[2]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[1]} -radix hexadecimal} {{/tb_f11/cpu/data/pin_m[0]} -radix hexadecimal}} -subitemconfig {{/tb_f11/cpu/data/pin_m[15]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[14]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[13]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[12]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[11]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[10]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[9]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[8]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[7]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[6]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[5]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[4]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[3]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[2]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[1]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/pin_m[0]} {-height 15 -radix hexadecimal}} /tb_f11/cpu/data/pin_m
add wave -noupdate -group 302 -group registers -label R0 -radix octal -childformat {{{/tb_f11/cpu/data/r[0][15]} -radix octal} {{/tb_f11/cpu/data/r[0][14]} -radix octal} {{/tb_f11/cpu/data/r[0][13]} -radix octal} {{/tb_f11/cpu/data/r[0][12]} -radix octal} {{/tb_f11/cpu/data/r[0][11]} -radix octal} {{/tb_f11/cpu/data/r[0][10]} -radix octal} {{/tb_f11/cpu/data/r[0][9]} -radix octal} {{/tb_f11/cpu/data/r[0][8]} -radix octal} {{/tb_f11/cpu/data/r[0][7]} -radix octal} {{/tb_f11/cpu/data/r[0][6]} -radix octal} {{/tb_f11/cpu/data/r[0][5]} -radix octal} {{/tb_f11/cpu/data/r[0][4]} -radix octal} {{/tb_f11/cpu/data/r[0][3]} -radix octal} {{/tb_f11/cpu/data/r[0][2]} -radix octal} {{/tb_f11/cpu/data/r[0][1]} -radix octal} {{/tb_f11/cpu/data/r[0][0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/r[0][15]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][14]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][13]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][12]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][11]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][10]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][9]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][8]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][7]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][6]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][5]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][4]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][3]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][2]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][1]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[0][0]} {-height 15 -radix octal}} {/tb_f11/cpu/data/r[0]}
add wave -noupdate -group 302 -group registers -label R1 -radix octal -childformat {{{/tb_f11/cpu/data/r[1][15]} -radix octal} {{/tb_f11/cpu/data/r[1][14]} -radix octal} {{/tb_f11/cpu/data/r[1][13]} -radix octal} {{/tb_f11/cpu/data/r[1][12]} -radix octal} {{/tb_f11/cpu/data/r[1][11]} -radix octal} {{/tb_f11/cpu/data/r[1][10]} -radix octal} {{/tb_f11/cpu/data/r[1][9]} -radix octal} {{/tb_f11/cpu/data/r[1][8]} -radix octal} {{/tb_f11/cpu/data/r[1][7]} -radix octal} {{/tb_f11/cpu/data/r[1][6]} -radix octal} {{/tb_f11/cpu/data/r[1][5]} -radix octal} {{/tb_f11/cpu/data/r[1][4]} -radix octal} {{/tb_f11/cpu/data/r[1][3]} -radix octal} {{/tb_f11/cpu/data/r[1][2]} -radix octal} {{/tb_f11/cpu/data/r[1][1]} -radix octal} {{/tb_f11/cpu/data/r[1][0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/r[1][15]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][14]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][13]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][12]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][11]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][10]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][9]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][8]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][7]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][6]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][5]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][4]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][3]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][2]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][1]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[1][0]} {-height 15 -radix octal}} {/tb_f11/cpu/data/r[1]}
add wave -noupdate -group 302 -group registers -label R2 -radix octal {/tb_f11/cpu/data/r[2]}
add wave -noupdate -group 302 -group registers -label R3 -radix octal {/tb_f11/cpu/data/r[3]}
add wave -noupdate -group 302 -group registers -label R4 -radix octal {/tb_f11/cpu/data/r[4]}
add wave -noupdate -group 302 -group registers -label R5 -radix octal {/tb_f11/cpu/data/r[5]}
add wave -noupdate -group 302 -group registers -label SP0 -radix octal {/tb_f11/cpu/data/r[6]}
add wave -noupdate -group 302 -group registers -label PC -radix octal {/tb_f11/cpu/data/r[7]}
add wave -noupdate -group 302 -group registers -label PSW -radix octal -childformat {{{/tb_f11/cpu/data/r[8][15]} -radix octal} {{/tb_f11/cpu/data/r[8][14]} -radix octal} {{/tb_f11/cpu/data/r[8][13]} -radix octal} {{/tb_f11/cpu/data/r[8][12]} -radix octal} {{/tb_f11/cpu/data/r[8][11]} -radix octal} {{/tb_f11/cpu/data/r[8][10]} -radix octal} {{/tb_f11/cpu/data/r[8][9]} -radix octal} {{/tb_f11/cpu/data/r[8][8]} -radix octal} {{/tb_f11/cpu/data/r[8][7]} -radix octal} {{/tb_f11/cpu/data/r[8][6]} -radix octal} {{/tb_f11/cpu/data/r[8][5]} -radix octal} {{/tb_f11/cpu/data/r[8][4]} -radix octal} {{/tb_f11/cpu/data/r[8][3]} -radix octal} {{/tb_f11/cpu/data/r[8][2]} -radix octal} {{/tb_f11/cpu/data/r[8][1]} -radix octal} {{/tb_f11/cpu/data/r[8][0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/r[8][15]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][14]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][13]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][12]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][11]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][10]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][9]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][8]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][7]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][6]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][5]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][4]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][3]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][2]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][1]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[8][0]} {-height 15 -radix octal}} {/tb_f11/cpu/data/r[8]}
add wave -noupdate -group 302 -group registers -label R9 -radix octal -childformat {{{/tb_f11/cpu/data/r[9][15]} -radix octal} {{/tb_f11/cpu/data/r[9][14]} -radix octal} {{/tb_f11/cpu/data/r[9][13]} -radix octal} {{/tb_f11/cpu/data/r[9][12]} -radix octal} {{/tb_f11/cpu/data/r[9][11]} -radix octal} {{/tb_f11/cpu/data/r[9][10]} -radix octal} {{/tb_f11/cpu/data/r[9][9]} -radix octal} {{/tb_f11/cpu/data/r[9][8]} -radix octal} {{/tb_f11/cpu/data/r[9][7]} -radix octal} {{/tb_f11/cpu/data/r[9][6]} -radix octal} {{/tb_f11/cpu/data/r[9][5]} -radix octal} {{/tb_f11/cpu/data/r[9][4]} -radix octal} {{/tb_f11/cpu/data/r[9][3]} -radix octal} {{/tb_f11/cpu/data/r[9][2]} -radix octal} {{/tb_f11/cpu/data/r[9][1]} -radix octal} {{/tb_f11/cpu/data/r[9][0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/r[9][15]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][14]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][13]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][12]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][11]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][10]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][9]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][8]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][7]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][6]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][5]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][4]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][3]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][2]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][1]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[9][0]} {-height 15 -radix octal}} {/tb_f11/cpu/data/r[9]}
add wave -noupdate -group 302 -group registers -label R10 -radix octal -childformat {{{/tb_f11/cpu/data/r[10][15]} -radix octal} {{/tb_f11/cpu/data/r[10][14]} -radix octal} {{/tb_f11/cpu/data/r[10][13]} -radix octal} {{/tb_f11/cpu/data/r[10][12]} -radix octal} {{/tb_f11/cpu/data/r[10][11]} -radix octal} {{/tb_f11/cpu/data/r[10][10]} -radix octal} {{/tb_f11/cpu/data/r[10][9]} -radix octal} {{/tb_f11/cpu/data/r[10][8]} -radix octal} {{/tb_f11/cpu/data/r[10][7]} -radix octal} {{/tb_f11/cpu/data/r[10][6]} -radix octal} {{/tb_f11/cpu/data/r[10][5]} -radix octal} {{/tb_f11/cpu/data/r[10][4]} -radix octal} {{/tb_f11/cpu/data/r[10][3]} -radix octal} {{/tb_f11/cpu/data/r[10][2]} -radix octal} {{/tb_f11/cpu/data/r[10][1]} -radix octal} {{/tb_f11/cpu/data/r[10][0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/r[10][15]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][14]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][13]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][12]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][11]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][10]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][9]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][8]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][7]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][6]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][5]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][4]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][3]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][2]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][1]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[10][0]} {-height 15 -radix octal}} {/tb_f11/cpu/data/r[10]}
add wave -noupdate -group 302 -group registers -label R11 -radix octal {/tb_f11/cpu/data/r[11]}
add wave -noupdate -group 302 -group registers -label SP1 -radix octal {/tb_f11/cpu/data/r[12]}
add wave -noupdate -group 302 -group registers -label SP3 -radix octal {/tb_f11/cpu/data/r[13]}
add wave -noupdate -group 302 -group registers -label R14 -radix octal -childformat {{{/tb_f11/cpu/data/r[14][15]} -radix octal} {{/tb_f11/cpu/data/r[14][14]} -radix octal} {{/tb_f11/cpu/data/r[14][13]} -radix octal} {{/tb_f11/cpu/data/r[14][12]} -radix octal} {{/tb_f11/cpu/data/r[14][11]} -radix octal} {{/tb_f11/cpu/data/r[14][10]} -radix octal} {{/tb_f11/cpu/data/r[14][9]} -radix octal} {{/tb_f11/cpu/data/r[14][8]} -radix octal} {{/tb_f11/cpu/data/r[14][7]} -radix octal} {{/tb_f11/cpu/data/r[14][6]} -radix octal} {{/tb_f11/cpu/data/r[14][5]} -radix octal} {{/tb_f11/cpu/data/r[14][4]} -radix octal} {{/tb_f11/cpu/data/r[14][3]} -radix octal} {{/tb_f11/cpu/data/r[14][2]} -radix octal} {{/tb_f11/cpu/data/r[14][1]} -radix octal} {{/tb_f11/cpu/data/r[14][0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/r[14][15]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][14]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][13]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][12]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][11]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][10]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][9]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][8]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][7]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][6]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][5]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][4]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][3]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][2]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][1]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[14][0]} {-height 15 -radix octal}} {/tb_f11/cpu/data/r[14]}
add wave -noupdate -group 302 -group registers -label R15 -radix octal -childformat {{{/tb_f11/cpu/data/r[15][15]} -radix octal} {{/tb_f11/cpu/data/r[15][14]} -radix octal} {{/tb_f11/cpu/data/r[15][13]} -radix octal} {{/tb_f11/cpu/data/r[15][12]} -radix octal} {{/tb_f11/cpu/data/r[15][11]} -radix octal} {{/tb_f11/cpu/data/r[15][10]} -radix octal} {{/tb_f11/cpu/data/r[15][9]} -radix octal} {{/tb_f11/cpu/data/r[15][8]} -radix octal} {{/tb_f11/cpu/data/r[15][7]} -radix octal} {{/tb_f11/cpu/data/r[15][6]} -radix octal} {{/tb_f11/cpu/data/r[15][5]} -radix octal} {{/tb_f11/cpu/data/r[15][4]} -radix octal} {{/tb_f11/cpu/data/r[15][3]} -radix octal} {{/tb_f11/cpu/data/r[15][2]} -radix octal} {{/tb_f11/cpu/data/r[15][1]} -radix octal} {{/tb_f11/cpu/data/r[15][0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/r[15][15]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][14]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][13]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][12]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][11]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][10]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][9]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][8]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][7]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][6]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][5]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][4]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][3]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][2]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][1]} {-height 15 -radix octal} {/tb_f11/cpu/data/r[15][0]} {-height 15 -radix octal}} {/tb_f11/cpu/data/r[15]}
add wave -noupdate -group 302 -group alu -radix octal -childformat {{{/tb_f11/cpu/data/pa[15]} -radix octal} {{/tb_f11/cpu/data/pa[14]} -radix octal} {{/tb_f11/cpu/data/pa[13]} -radix octal} {{/tb_f11/cpu/data/pa[12]} -radix octal} {{/tb_f11/cpu/data/pa[11]} -radix octal} {{/tb_f11/cpu/data/pa[10]} -radix octal} {{/tb_f11/cpu/data/pa[9]} -radix octal} {{/tb_f11/cpu/data/pa[8]} -radix octal} {{/tb_f11/cpu/data/pa[7]} -radix octal} {{/tb_f11/cpu/data/pa[6]} -radix octal} {{/tb_f11/cpu/data/pa[5]} -radix octal} {{/tb_f11/cpu/data/pa[4]} -radix octal} {{/tb_f11/cpu/data/pa[3]} -radix octal} {{/tb_f11/cpu/data/pa[2]} -radix octal} {{/tb_f11/cpu/data/pa[1]} -radix octal} {{/tb_f11/cpu/data/pa[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/pa[15]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[14]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[13]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[12]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[11]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[10]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[9]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[8]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[7]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[6]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[5]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[4]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[3]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[2]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[1]} {-height 15 -radix octal} {/tb_f11/cpu/data/pa[0]} {-height 15 -radix octal}} /tb_f11/cpu/data/pa
add wave -noupdate -group 302 -group alu -radix octal -childformat {{{/tb_f11/cpu/data/pb[15]} -radix octal} {{/tb_f11/cpu/data/pb[14]} -radix octal} {{/tb_f11/cpu/data/pb[13]} -radix octal} {{/tb_f11/cpu/data/pb[12]} -radix octal} {{/tb_f11/cpu/data/pb[11]} -radix octal} {{/tb_f11/cpu/data/pb[10]} -radix octal} {{/tb_f11/cpu/data/pb[9]} -radix octal} {{/tb_f11/cpu/data/pb[8]} -radix octal} {{/tb_f11/cpu/data/pb[7]} -radix octal} {{/tb_f11/cpu/data/pb[6]} -radix octal} {{/tb_f11/cpu/data/pb[5]} -radix octal} {{/tb_f11/cpu/data/pb[4]} -radix octal} {{/tb_f11/cpu/data/pb[3]} -radix octal} {{/tb_f11/cpu/data/pb[2]} -radix octal} {{/tb_f11/cpu/data/pb[1]} -radix octal} {{/tb_f11/cpu/data/pb[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/pb[15]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[14]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[13]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[12]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[11]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[10]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[9]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[8]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[7]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[6]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[5]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[4]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[3]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[2]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[1]} {-height 15 -radix octal} {/tb_f11/cpu/data/pb[0]} {-height 15 -radix octal}} /tb_f11/cpu/data/pb
add wave -noupdate -group 302 -group alu -radix octal -childformat {{{/tb_f11/cpu/data/b[15]} -radix octal} {{/tb_f11/cpu/data/b[14]} -radix octal} {{/tb_f11/cpu/data/b[13]} -radix octal} {{/tb_f11/cpu/data/b[12]} -radix octal} {{/tb_f11/cpu/data/b[11]} -radix octal} {{/tb_f11/cpu/data/b[10]} -radix octal} {{/tb_f11/cpu/data/b[9]} -radix octal} {{/tb_f11/cpu/data/b[8]} -radix octal} {{/tb_f11/cpu/data/b[7]} -radix octal} {{/tb_f11/cpu/data/b[6]} -radix octal} {{/tb_f11/cpu/data/b[5]} -radix octal} {{/tb_f11/cpu/data/b[4]} -radix octal} {{/tb_f11/cpu/data/b[3]} -radix octal} {{/tb_f11/cpu/data/b[2]} -radix octal} {{/tb_f11/cpu/data/b[1]} -radix octal} {{/tb_f11/cpu/data/b[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/b[15]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[14]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[13]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[12]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[11]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[10]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[9]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[8]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[7]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[6]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[5]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[4]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[3]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[2]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[1]} {-height 15 -radix octal} {/tb_f11/cpu/data/b[0]} {-height 15 -radix octal}} /tb_f11/cpu/data/b
add wave -noupdate -group 302 -group alu -radix octal -childformat {{{/tb_f11/cpu/data/d[15]} -radix octal} {{/tb_f11/cpu/data/d[14]} -radix octal} {{/tb_f11/cpu/data/d[13]} -radix octal} {{/tb_f11/cpu/data/d[12]} -radix octal} {{/tb_f11/cpu/data/d[11]} -radix octal} {{/tb_f11/cpu/data/d[10]} -radix octal} {{/tb_f11/cpu/data/d[9]} -radix octal} {{/tb_f11/cpu/data/d[8]} -radix octal} {{/tb_f11/cpu/data/d[7]} -radix octal} {{/tb_f11/cpu/data/d[6]} -radix octal} {{/tb_f11/cpu/data/d[5]} -radix octal} {{/tb_f11/cpu/data/d[4]} -radix octal} {{/tb_f11/cpu/data/d[3]} -radix octal} {{/tb_f11/cpu/data/d[2]} -radix octal} {{/tb_f11/cpu/data/d[1]} -radix octal} {{/tb_f11/cpu/data/d[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/d[15]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[14]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[13]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[12]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[11]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[10]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[9]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[8]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[7]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[6]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[5]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[4]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[3]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[2]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[1]} {-height 15 -radix octal} {/tb_f11/cpu/data/d[0]} {-height 15 -radix octal}} /tb_f11/cpu/data/d
add wave -noupdate -group 302 -group alu -radix octal -childformat {{{/tb_f11/cpu/data/af[15]} -radix octal} {{/tb_f11/cpu/data/af[14]} -radix octal} {{/tb_f11/cpu/data/af[13]} -radix octal} {{/tb_f11/cpu/data/af[12]} -radix octal} {{/tb_f11/cpu/data/af[11]} -radix octal} {{/tb_f11/cpu/data/af[10]} -radix octal} {{/tb_f11/cpu/data/af[9]} -radix octal} {{/tb_f11/cpu/data/af[8]} -radix octal} {{/tb_f11/cpu/data/af[7]} -radix octal} {{/tb_f11/cpu/data/af[6]} -radix octal} {{/tb_f11/cpu/data/af[5]} -radix octal} {{/tb_f11/cpu/data/af[4]} -radix octal} {{/tb_f11/cpu/data/af[3]} -radix octal} {{/tb_f11/cpu/data/af[2]} -radix octal} {{/tb_f11/cpu/data/af[1]} -radix octal} {{/tb_f11/cpu/data/af[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/af[15]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[14]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[13]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[12]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[11]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[10]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[9]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[8]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[7]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[6]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[5]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[4]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[3]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[2]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[1]} {-height 15 -radix octal} {/tb_f11/cpu/data/af[0]} {-height 15 -radix octal}} /tb_f11/cpu/data/af
add wave -noupdate -group 302 -group alu -radix octal -childformat {{{/tb_f11/cpu/data/afr[15]} -radix octal} {{/tb_f11/cpu/data/afr[14]} -radix octal} {{/tb_f11/cpu/data/afr[13]} -radix octal} {{/tb_f11/cpu/data/afr[12]} -radix octal} {{/tb_f11/cpu/data/afr[11]} -radix octal} {{/tb_f11/cpu/data/afr[10]} -radix octal} {{/tb_f11/cpu/data/afr[9]} -radix octal} {{/tb_f11/cpu/data/afr[8]} -radix octal} {{/tb_f11/cpu/data/afr[7]} -radix octal} {{/tb_f11/cpu/data/afr[6]} -radix octal} {{/tb_f11/cpu/data/afr[5]} -radix octal} {{/tb_f11/cpu/data/afr[4]} -radix octal} {{/tb_f11/cpu/data/afr[3]} -radix octal} {{/tb_f11/cpu/data/afr[2]} -radix octal} {{/tb_f11/cpu/data/afr[1]} -radix octal} {{/tb_f11/cpu/data/afr[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/afr[15]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[14]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[13]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[12]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[11]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[10]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[9]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[8]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[7]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[6]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[5]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[4]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[3]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[2]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[1]} {-height 15 -radix octal} {/tb_f11/cpu/data/afr[0]} {-height 15 -radix octal}} /tb_f11/cpu/data/afr
add wave -noupdate -group 302 -group alu -radix octal /tb_f11/cpu/data/ac
add wave -noupdate -group 302 -group alu /tb_f11/cpu/data/ac_lsb
add wave -noupdate -group 302 -group alu -radix octal -childformat {{{/tb_f11/cpu/data/di[15]} -radix octal} {{/tb_f11/cpu/data/di[14]} -radix octal} {{/tb_f11/cpu/data/di[13]} -radix octal} {{/tb_f11/cpu/data/di[12]} -radix octal} {{/tb_f11/cpu/data/di[11]} -radix octal} {{/tb_f11/cpu/data/di[10]} -radix octal} {{/tb_f11/cpu/data/di[9]} -radix octal} {{/tb_f11/cpu/data/di[8]} -radix octal} {{/tb_f11/cpu/data/di[7]} -radix octal} {{/tb_f11/cpu/data/di[6]} -radix octal} {{/tb_f11/cpu/data/di[5]} -radix octal} {{/tb_f11/cpu/data/di[4]} -radix octal} {{/tb_f11/cpu/data/di[3]} -radix octal} {{/tb_f11/cpu/data/di[2]} -radix octal} {{/tb_f11/cpu/data/di[1]} -radix octal} {{/tb_f11/cpu/data/di[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/di[15]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[14]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[13]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[12]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[11]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[10]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[9]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[8]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[7]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[6]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[5]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[4]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[3]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[2]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[1]} {-height 15 -radix octal} {/tb_f11/cpu/data/di[0]} {-height 15 -radix octal}} /tb_f11/cpu/data/di
add wave -noupdate -group 302 -group alu -radix octal -childformat {{{/tb_f11/cpu/data/dx[15]} -radix octal} {{/tb_f11/cpu/data/dx[14]} -radix octal} {{/tb_f11/cpu/data/dx[13]} -radix octal} {{/tb_f11/cpu/data/dx[12]} -radix octal} {{/tb_f11/cpu/data/dx[11]} -radix octal} {{/tb_f11/cpu/data/dx[10]} -radix octal} {{/tb_f11/cpu/data/dx[9]} -radix octal} {{/tb_f11/cpu/data/dx[8]} -radix octal} {{/tb_f11/cpu/data/dx[7]} -radix octal} {{/tb_f11/cpu/data/dx[6]} -radix octal} {{/tb_f11/cpu/data/dx[5]} -radix octal} {{/tb_f11/cpu/data/dx[4]} -radix octal} {{/tb_f11/cpu/data/dx[3]} -radix octal} {{/tb_f11/cpu/data/dx[2]} -radix octal} {{/tb_f11/cpu/data/dx[1]} -radix octal} {{/tb_f11/cpu/data/dx[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/dx[15]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[14]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[13]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[12]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[11]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[10]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[9]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[8]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[7]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[6]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[5]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[4]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[3]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[2]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[1]} {-height 15 -radix octal} {/tb_f11/cpu/data/dx[0]} {-height 15 -radix octal}} /tb_f11/cpu/data/dx
add wave -noupdate -group 302 -group alu -radix octal -childformat {{{/tb_f11/cpu/data/fx[15]} -radix octal} {{/tb_f11/cpu/data/fx[14]} -radix octal} {{/tb_f11/cpu/data/fx[13]} -radix octal} {{/tb_f11/cpu/data/fx[12]} -radix octal} {{/tb_f11/cpu/data/fx[11]} -radix octal} {{/tb_f11/cpu/data/fx[10]} -radix octal} {{/tb_f11/cpu/data/fx[9]} -radix octal} {{/tb_f11/cpu/data/fx[8]} -radix octal} {{/tb_f11/cpu/data/fx[7]} -radix octal} {{/tb_f11/cpu/data/fx[6]} -radix octal} {{/tb_f11/cpu/data/fx[5]} -radix octal} {{/tb_f11/cpu/data/fx[4]} -radix octal} {{/tb_f11/cpu/data/fx[3]} -radix octal} {{/tb_f11/cpu/data/fx[2]} -radix octal} {{/tb_f11/cpu/data/fx[1]} -radix octal} {{/tb_f11/cpu/data/fx[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/fx[15]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[14]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[13]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[12]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[11]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[10]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[9]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[8]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[7]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[6]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[5]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[4]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[3]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[2]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[1]} {-height 15 -radix octal} {/tb_f11/cpu/data/fx[0]} {-height 15 -radix octal}} /tb_f11/cpu/data/fx
add wave -noupdate -group 302 -group alu -group fx_en /tb_f11/cpu/data/fx_en
add wave -noupdate -group 302 -group alu -group fx_en /tb_f11/cpu/data/fx_en0
add wave -noupdate -group 302 -group alu -group fx_en /tb_f11/cpu/data/fx_en1
add wave -noupdate -group 302 -group alu -group fx_en /tb_f11/cpu/data/fx_en2
add wave -noupdate -group 302 -group alu -group fx_en -radix hexadecimal -childformat {{{/tb_f11/cpu/data/fx_ren[3]} -radix hexadecimal} {{/tb_f11/cpu/data/fx_ren[2]} -radix hexadecimal} {{/tb_f11/cpu/data/fx_ren[1]} -radix hexadecimal} {{/tb_f11/cpu/data/fx_ren[0]} -radix hexadecimal}} -subitemconfig {{/tb_f11/cpu/data/fx_ren[3]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/fx_ren[2]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/fx_ren[1]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/fx_ren[0]} {-height 15 -radix hexadecimal}} /tb_f11/cpu/data/fx_ren
add wave -noupdate -group 302 -group alu -group alu_x /tb_f11/cpu/data/alu_a
add wave -noupdate -group 302 -group alu -group alu_x /tb_f11/cpu/data/alu_b
add wave -noupdate -group 302 -group alu -group alu_x /tb_f11/cpu/data/alu_c
add wave -noupdate -group 302 -group alu -group alu_x /tb_f11/cpu/data/alu_d
add wave -noupdate -group 302 -group alu -group alu_x /tb_f11/cpu/data/alu_e
add wave -noupdate -group 302 -group alu -group alu_x /tb_f11/cpu/data/alu_f
add wave -noupdate -group 302 -group alu -group alu_x /tb_f11/cpu/data/alu_g
add wave -noupdate -group 302 -group alu -group alu_x /tb_f11/cpu/data/alu_h
add wave -noupdate -group 302 -group alu -group alu_x /tb_f11/cpu/data/swap
add wave -noupdate -group 302 -group alu -group alu_x /tb_f11/cpu/data/sext
add wave -noupdate -group 302 -group alu /tb_f11/cpu/data/pa_en
add wave -noupdate -group 302 -group alu /tb_f11/cpu/data/bra
add wave -noupdate -group 302 -group alu /tb_f11/cpu/data/mbra
add wave -noupdate -group 302 -group alu -radix unsigned -childformat {{{/tb_f11/cpu/data/sa[3]} -radix decimal} {{/tb_f11/cpu/data/sa[2]} -radix decimal} {{/tb_f11/cpu/data/sa[1]} -radix decimal} {{/tb_f11/cpu/data/sa[0]} -radix decimal}} -subitemconfig {{/tb_f11/cpu/data/sa[3]} {-height 15 -radix decimal} {/tb_f11/cpu/data/sa[2]} {-height 15 -radix decimal} {/tb_f11/cpu/data/sa[1]} {-height 15 -radix decimal} {/tb_f11/cpu/data/sa[0]} {-height 15 -radix decimal}} /tb_f11/cpu/data/sa
add wave -noupdate -group 302 -group alu -radix unsigned -childformat {{{/tb_f11/cpu/data/sb[3]} -radix unsigned} {{/tb_f11/cpu/data/sb[2]} -radix unsigned} {{/tb_f11/cpu/data/sb[1]} -radix unsigned} {{/tb_f11/cpu/data/sb[0]} -radix unsigned}} -subitemconfig {{/tb_f11/cpu/data/sb[3]} {-height 15 -radix unsigned} {/tb_f11/cpu/data/sb[2]} {-height 15 -radix unsigned} {/tb_f11/cpu/data/sb[1]} {-height 15 -radix unsigned} {/tb_f11/cpu/data/sb[0]} {-height 15 -radix unsigned}} /tb_f11/cpu/data/sb
add wave -noupdate -group 302 -radix octal -childformat {{{/tb_f11/cpu/data/ir[15]} -radix octal} {{/tb_f11/cpu/data/ir[14]} -radix octal} {{/tb_f11/cpu/data/ir[13]} -radix octal} {{/tb_f11/cpu/data/ir[12]} -radix octal} {{/tb_f11/cpu/data/ir[11]} -radix octal} {{/tb_f11/cpu/data/ir[10]} -radix octal} {{/tb_f11/cpu/data/ir[9]} -radix octal} {{/tb_f11/cpu/data/ir[8]} -radix octal} {{/tb_f11/cpu/data/ir[7]} -radix octal} {{/tb_f11/cpu/data/ir[6]} -radix octal} {{/tb_f11/cpu/data/ir[5]} -radix octal} {{/tb_f11/cpu/data/ir[4]} -radix octal} {{/tb_f11/cpu/data/ir[3]} -radix octal} {{/tb_f11/cpu/data/ir[2]} -radix octal} {{/tb_f11/cpu/data/ir[1]} -radix octal} {{/tb_f11/cpu/data/ir[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/data/ir[15]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[14]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[13]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[12]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[11]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[10]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[9]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[8]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[7]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[6]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[5]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[4]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[3]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[2]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[1]} {-height 15 -radix octal} {/tb_f11/cpu/data/ir[0]} {-height 15 -radix octal}} /tb_f11/cpu/data/ir
add wave -noupdate -group 302 -group data.psw /tb_f11/cpu/data/psw_stb
add wave -noupdate -group 302 -group data.psw /tb_f11/cpu/data/wpsw_c
add wave -noupdate -group 302 -group data.psw /tb_f11/cpu/data/wpsw_n
add wave -noupdate -group 302 -group data.psw /tb_f11/cpu/data/wpsw_v
add wave -noupdate -group 302 -group data.psw /tb_f11/cpu/data/wpsw_zh
add wave -noupdate -group 302 -group data.psw /tb_f11/cpu/data/wpsw_zl
add wave -noupdate -group 302 -group data.psw /tb_f11/cpu/data/cp_715
add wave -noupdate -group 302 -group data.psw /tb_f11/cpu/data/cp_816
add wave -noupdate -group 302 -radix hexadecimal -childformat {{{/tb_f11/cpu/data/mo[15]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[14]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[13]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[12]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[11]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[10]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[9]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[8]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[7]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[6]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[5]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[4]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[3]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[2]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[1]} -radix hexadecimal} {{/tb_f11/cpu/data/mo[0]} -radix hexadecimal}} -subitemconfig {{/tb_f11/cpu/data/mo[15]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[14]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[13]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[12]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[11]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[10]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[9]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[8]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[7]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[6]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[5]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[4]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[3]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[2]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[1]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/data/mo[0]} {-height 15 -radix hexadecimal}} /tb_f11/cpu/data/mo
add wave -noupdate -group 302 /tb_f11/cpu/data/moe
add wave -noupdate -group 302 /tb_f11/cpu/data/doe
add wave -noupdate -group 302 /tb_f11/cpu/data/db_oeh
add wave -noupdate -group 302 /tb_f11/cpu/data/db_oel
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/astb
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/badr
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/bcyc
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/bsyn
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/d0c
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/io_a0c
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/io_a0
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/io_psw
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/io_pswc
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/ystk
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/ystk0
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/psel
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/m15c
add wave -noupdate -group 302 -group dbus /tb_f11/cpu/data/rinit
add wave -noupdate -group 302 -radix hexadecimal /tb_f11/cpu/data/m
add wave -noupdate -group 303 /tb_f11/cpu/control/pin_clk
add wave -noupdate -group 303 -group pins -radix hexadecimal -childformat {{{/tb_f11/cpu/control/pin_m[15]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[14]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[13]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[12]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[11]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[10]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[9]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[8]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[7]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[6]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[5]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[4]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[3]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[2]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[1]} -radix hexadecimal} {{/tb_f11/cpu/control/pin_m[0]} -radix hexadecimal}} -expand -subitemconfig {{/tb_f11/cpu/control/pin_m[15]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[14]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[13]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[12]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[11]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[10]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[9]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[8]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[7]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[6]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[5]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[4]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[3]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[2]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[1]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/pin_m[0]} {-height 15 -radix hexadecimal}} /tb_f11/cpu/control/pin_m
add wave -noupdate -group 303 -group pins -radix octal -childformat {{{/tb_f11/cpu/control/pin_ad[15]} -radix octal} {{/tb_f11/cpu/control/pin_ad[14]} -radix octal} {{/tb_f11/cpu/control/pin_ad[13]} -radix octal} {{/tb_f11/cpu/control/pin_ad[12]} -radix octal} {{/tb_f11/cpu/control/pin_ad[11]} -radix octal} {{/tb_f11/cpu/control/pin_ad[10]} -radix octal} {{/tb_f11/cpu/control/pin_ad[9]} -radix octal} {{/tb_f11/cpu/control/pin_ad[8]} -radix octal} {{/tb_f11/cpu/control/pin_ad[7]} -radix octal} {{/tb_f11/cpu/control/pin_ad[6]} -radix octal} {{/tb_f11/cpu/control/pin_ad[5]} -radix octal} {{/tb_f11/cpu/control/pin_ad[4]} -radix octal} {{/tb_f11/cpu/control/pin_ad[3]} -radix octal} {{/tb_f11/cpu/control/pin_ad[2]} -radix octal} {{/tb_f11/cpu/control/pin_ad[1]} -radix octal} {{/tb_f11/cpu/control/pin_ad[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/control/pin_ad[15]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[14]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[13]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[12]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[11]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[10]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[9]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[8]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[7]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[6]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[5]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[4]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[3]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[2]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[1]} {-height 15 -radix octal} {/tb_f11/cpu/control/pin_ad[0]} {-height 15 -radix octal}} /tb_f11/cpu/control/pin_ad
add wave -noupdate -group 303 -group pins /tb_f11/cpu/control/pin_cs_n
add wave -noupdate -group 303 -group pins /tb_f11/cpu/control/pin_ez_n
add wave -noupdate -group 303 -group pins /tb_f11/cpu/control/pin_rst
add wave -noupdate -group 303 -radix hexadecimal -childformat {{{/tb_f11/cpu/control/nar[8]} -radix hexadecimal} {{/tb_f11/cpu/control/nar[7]} -radix hexadecimal} {{/tb_f11/cpu/control/nar[6]} -radix hexadecimal} {{/tb_f11/cpu/control/nar[5]} -radix hexadecimal} {{/tb_f11/cpu/control/nar[4]} -radix hexadecimal} {{/tb_f11/cpu/control/nar[3]} -radix hexadecimal} {{/tb_f11/cpu/control/nar[2]} -radix hexadecimal} {{/tb_f11/cpu/control/nar[1]} -radix hexadecimal} {{/tb_f11/cpu/control/nar[0]} -radix hexadecimal}} -subitemconfig {{/tb_f11/cpu/control/nar[8]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/nar[7]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/nar[6]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/nar[5]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/nar[4]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/nar[3]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/nar[2]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/nar[1]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/nar[0]} {-height 15 -radix hexadecimal}} /tb_f11/cpu/control/nar
add wave -noupdate -group 303 -radix hexadecimal /tb_f11/cpu/control/m
add wave -noupdate -group 303 -radix hexadecimal -childformat {{{/tb_f11/cpu/control/na[8]} -radix hexadecimal} {{/tb_f11/cpu/control/na[7]} -radix hexadecimal} {{/tb_f11/cpu/control/na[6]} -radix hexadecimal} {{/tb_f11/cpu/control/na[5]} -radix hexadecimal} {{/tb_f11/cpu/control/na[4]} -radix hexadecimal} {{/tb_f11/cpu/control/na[3]} -radix hexadecimal} {{/tb_f11/cpu/control/na[2]} -radix hexadecimal} {{/tb_f11/cpu/control/na[1]} -radix hexadecimal} {{/tb_f11/cpu/control/na[0]} -radix hexadecimal}} -subitemconfig {{/tb_f11/cpu/control/na[8]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/na[7]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/na[6]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/na[5]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/na[4]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/na[3]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/na[2]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/na[1]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/na[0]} {-height 15 -radix hexadecimal}} /tb_f11/cpu/control/na
add wave -noupdate -group 303 -radix hexadecimal /tb_f11/cpu/control/mc
add wave -noupdate -group 303 -group psw /tb_f11/cpu/control/tbit
add wave -noupdate -group 303 -group psw /tb_f11/cpu/control/tbit_stb
add wave -noupdate -group 303 -group psw /tb_f11/cpu/control/tgl_axt
add wave -noupdate -group 303 -group psw -radix octal /tb_f11/cpu/control/pri
add wave -noupdate -group 303 -group psw /tb_f11/cpu/control/pri_stb
add wave -noupdate -group 303 -group psw /tb_f11/cpu/control/lplm
add wave -noupdate -group 303 -group psw /tb_f11/cpu/control/wpsw
add wave -noupdate -group 303 -group Control /tb_f11/cpu/control/rni
add wave -noupdate -group 303 -group Control /tb_f11/cpu/control/rnit
add wave -noupdate -group 303 -group Control /tb_f11/cpu/control/sovf
add wave -noupdate -group 303 -group Control /tb_f11/cpu/control/axt
add wave -noupdate -group 303 -group Control /tb_f11/cpu/control/axtt
add wave -noupdate -group 303 -group Control /tb_f11/cpu/control/cjmp
add wave -noupdate -group 303 -group Control /tb_f11/cpu/control/jump
add wave -noupdate -group 303 -group Control -radix hexadecimal -childformat {{{/tb_f11/cpu/control/d[15]} -radix hexadecimal} {{/tb_f11/cpu/control/d[14]} -radix hexadecimal} {{/tb_f11/cpu/control/d[13]} -radix hexadecimal} {{/tb_f11/cpu/control/d[12]} -radix hexadecimal} {{/tb_f11/cpu/control/d[11]} -radix hexadecimal} {{/tb_f11/cpu/control/d[10]} -radix hexadecimal} {{/tb_f11/cpu/control/d[9]} -radix hexadecimal} {{/tb_f11/cpu/control/d[8]} -radix hexadecimal} {{/tb_f11/cpu/control/d[7]} -radix hexadecimal} {{/tb_f11/cpu/control/d[6]} -radix hexadecimal} {{/tb_f11/cpu/control/d[5]} -radix hexadecimal} {{/tb_f11/cpu/control/d[4]} -radix hexadecimal} {{/tb_f11/cpu/control/d[3]} -radix hexadecimal} {{/tb_f11/cpu/control/d[2]} -radix hexadecimal} {{/tb_f11/cpu/control/d[1]} -radix hexadecimal} {{/tb_f11/cpu/control/d[0]} -radix hexadecimal}} -subitemconfig {{/tb_f11/cpu/control/d[15]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[14]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[13]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[12]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[11]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[10]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[9]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[8]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[7]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[6]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[5]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[4]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[3]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[2]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[1]} {-height 15 -radix hexadecimal} {/tb_f11/cpu/control/d[0]} {-height 15 -radix hexadecimal}} /tb_f11/cpu/control/d
add wave -noupdate -group 303 -group Control -radix octal -childformat {{{/tb_f11/cpu/control/d[15]} -radix octal} {{/tb_f11/cpu/control/d[14]} -radix octal} {{/tb_f11/cpu/control/d[13]} -radix octal} {{/tb_f11/cpu/control/d[12]} -radix octal} {{/tb_f11/cpu/control/d[11]} -radix octal} {{/tb_f11/cpu/control/d[10]} -radix octal} {{/tb_f11/cpu/control/d[9]} -radix octal} {{/tb_f11/cpu/control/d[8]} -radix octal} {{/tb_f11/cpu/control/d[7]} -radix octal} {{/tb_f11/cpu/control/d[6]} -radix octal} {{/tb_f11/cpu/control/d[5]} -radix octal} {{/tb_f11/cpu/control/d[4]} -radix octal} {{/tb_f11/cpu/control/d[3]} -radix octal} {{/tb_f11/cpu/control/d[2]} -radix octal} {{/tb_f11/cpu/control/d[1]} -radix octal} {{/tb_f11/cpu/control/d[0]} -radix octal}} -subitemconfig {{/tb_f11/cpu/control/d[15]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[14]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[13]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[12]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[11]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[10]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[9]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[8]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[7]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[6]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[5]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[4]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[3]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[2]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[1]} {-height 15 -radix octal} {/tb_f11/cpu/control/d[0]} {-height 15 -radix octal}} /tb_f11/cpu/control/d
add wave -noupdate -group 303 -group Control /tb_f11/cpu/control/di_stb
add wave -noupdate -group 303 -group Control /tb_f11/cpu/control/sovf
add wave -noupdate -group 303 -group Control /tb_f11/cpu/control/tbit
add wave -noupdate -group 303 -group decoder -radix hexadecimal /tb_f11/cpu/control/dcop
add wave -noupdate -group 303 -group decoder /tb_f11/cpu/control/na_111
add wave -noupdate -group 303 -group decoder /tb_f11/cpu/control/na_x00
add wave -noupdate -group 303 -group decoder /tb_f11/cpu/control/na_xxx
add wave -noupdate -group 303 -group decoder -radix hexadecimal /tb_f11/cpu/control/clr_na
TreeUpdate [SetDefaultTree]
configure wave -namecolwidth 171
configure wave -valuecolwidth 65
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {70999808 ps}
