onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group pins -label pin_ad_in -radix octal /tb_t11/cpu/pin_ad_in
add wave -noupdate -group pins -label pin_ad_out -radix octal /tb_t11/cpu/pin_ad_out
add wave -noupdate -group pins -label pin_ras_n /tb_t11/cpu/pin_ras_n
add wave -noupdate -group pins -label pin_cas_n /tb_t11/cpu/pin_cas_n
add wave -noupdate -group pins -label pin_pi /tb_t11/cpu/pin_pi
add wave -noupdate -group pins -label pin_wb_n /tb_t11/cpu/pin_wb_n
add wave -noupdate -group pins -label pin_sel -expand /tb_t11/cpu/pin_sel
add wave -noupdate -group pins -label pin_cp_n /tb_t11/cpu/pin_cp_n
add wave -noupdate -group pins -label pin_vec_n /tb_t11/cpu/pin_vec_n
add wave -noupdate -group pins -label pin_ready /tb_t11/cpu/pin_ready
add wave -noupdate -group pins -label vm_clk_ena /tb_t11/cpu/vm_clk_ena
add wave -noupdate -group pins -label vm_clk_n /tb_t11/cpu/vm_clk_n
add wave -noupdate -group pins -label vm_clk_p /tb_t11/cpu/vm_clk_p
add wave -noupdate -group pins -label vm_clk_slow /tb_t11/cpu/vm_clk_slow
add wave -noupdate -group pins -label vm_dclo /tb_t11/cpu/vm_dclo
add wave -noupdate -group pins -label vm_aclo /tb_t11/cpu/vm_aclo
add wave -noupdate -group pins -label vm_init /tb_t11/cpu/vm_init
add wave -noupdate -group pins -label vm_halt /tb_t11/cpu/vm_halt
add wave -noupdate -group clk -label t1 /tb_t11/cpu/t1
add wave -noupdate -group clk -label t2 /tb_t11/cpu/t2
add wave -noupdate -group clk -label t4 /tb_t11/cpu/t4
add wave -noupdate -group init -label dclo /tb_t11/cpu/dclo
add wave -noupdate -group init -label reset /tb_t11/cpu/reset
add wave -noupdate -group init -label hwclr /tb_t11/cpu/hwclr
add wave -noupdate -group init -label mr -radix octal -childformat {{{/tb_t11/cpu/mr[15]} -radix octal} {{/tb_t11/cpu/mr[14]} -radix octal} {{/tb_t11/cpu/mr[13]} -radix octal}} -subitemconfig {{/tb_t11/cpu/mr[15]} {-height 15 -radix octal} {/tb_t11/cpu/mr[14]} {-height 15 -radix octal} {/tb_t11/cpu/mr[13]} {-height 15 -radix octal}} /tb_t11/cpu/mr
add wave -noupdate -group init -label bt -radix octal /tb_t11/cpu/bt
add wave -noupdate -group init -label bt2_t /tb_t11/cpu/bt2_t
add wave -noupdate -group plm -label plm_stb /tb_t11/cpu/plm_stb
add wave -noupdate -group plm -label plm_rdy /tb_t11/cpu/plm_rdy
add wave -noupdate -group plm -label n -radix hexadecimal /tb_t11/cpu/n
add wave -noupdate -group plm -label na -radix hexadecimal -childformat {{{/tb_t11/cpu/na[7]} -radix hexadecimal} {{/tb_t11/cpu/na[6]} -radix hexadecimal} {{/tb_t11/cpu/na[5]} -radix hexadecimal} {{/tb_t11/cpu/na[4]} -radix hexadecimal} {{/tb_t11/cpu/na[3]} -radix hexadecimal} {{/tb_t11/cpu/na[2]} -radix hexadecimal} {{/tb_t11/cpu/na[1]} -radix hexadecimal} {{/tb_t11/cpu/na[0]} -radix hexadecimal}} -subitemconfig {{/tb_t11/cpu/na[7]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/na[6]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/na[5]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/na[4]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/na[3]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/na[2]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/na[1]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/na[0]} {-height 15 -radix hexadecimal}} /tb_t11/cpu/na
add wave -noupdate -group plm -label m -radix octal -childformat {{{/tb_t11/cpu/m[9]} -radix octal} {{/tb_t11/cpu/m[8]} -radix octal} {{/tb_t11/cpu/m[7]} -radix octal} {{/tb_t11/cpu/m[6]} -radix octal} {{/tb_t11/cpu/m[5]} -radix octal} {{/tb_t11/cpu/m[4]} -radix octal} {{/tb_t11/cpu/m[3]} -radix octal} {{/tb_t11/cpu/m[2]} -radix octal} {{/tb_t11/cpu/m[1]} -radix octal} {{/tb_t11/cpu/m[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/m[9]} {-height 15 -radix octal} {/tb_t11/cpu/m[8]} {-height 15 -radix octal} {/tb_t11/cpu/m[7]} {-height 15 -radix octal} {/tb_t11/cpu/m[6]} {-height 15 -radix octal} {/tb_t11/cpu/m[5]} {-height 15 -radix octal} {/tb_t11/cpu/m[4]} {-height 15 -radix octal} {/tb_t11/cpu/m[3]} {-height 15 -radix octal} {/tb_t11/cpu/m[2]} {-height 15 -radix octal} {/tb_t11/cpu/m[1]} {-height 15 -radix octal} {/tb_t11/cpu/m[0]} {-height 15 -radix octal}} /tb_t11/cpu/m
add wave -noupdate -group plm -label mi -radix octal -childformat {{{/tb_t11/cpu/mi[15]} -radix octal} {{/tb_t11/cpu/mi[14]} -radix octal} {{/tb_t11/cpu/mi[13]} -radix octal} {{/tb_t11/cpu/mi[12]} -radix octal} {{/tb_t11/cpu/mi[11]} -radix octal} {{/tb_t11/cpu/mi[10]} -radix octal} {{/tb_t11/cpu/mi[9]} -radix octal} {{/tb_t11/cpu/mi[8]} -radix octal} {{/tb_t11/cpu/mi[7]} -radix octal} {{/tb_t11/cpu/mi[6]} -radix octal}} -subitemconfig {{/tb_t11/cpu/mi[15]} {-height 15 -radix octal} {/tb_t11/cpu/mi[14]} {-height 15 -radix octal} {/tb_t11/cpu/mi[13]} {-height 15 -radix octal} {/tb_t11/cpu/mi[12]} {-height 15 -radix octal} {/tb_t11/cpu/mi[11]} {-height 15 -radix octal} {/tb_t11/cpu/mi[10]} {-height 15 -radix octal} {/tb_t11/cpu/mi[9]} {-height 15 -radix octal} {/tb_t11/cpu/mi[8]} {-height 15 -radix octal} {/tb_t11/cpu/mi[7]} {-height 15 -radix octal} {/tb_t11/cpu/mi[6]} {-height 15 -radix octal}} /tb_t11/cpu/mi
add wave -noupdate -group plm -label pla -radix hexadecimal -childformat {{{/tb_t11/cpu/pla[29]} -radix hexadecimal} {{/tb_t11/cpu/pla[28]} -radix hexadecimal} {{/tb_t11/cpu/pla[27]} -radix hexadecimal} {{/tb_t11/cpu/pla[26]} -radix hexadecimal} {{/tb_t11/cpu/pla[25]} -radix hexadecimal} {{/tb_t11/cpu/pla[24]} -radix hexadecimal} {{/tb_t11/cpu/pla[23]} -radix hexadecimal} {{/tb_t11/cpu/pla[22]} -radix hexadecimal} {{/tb_t11/cpu/pla[21]} -radix hexadecimal} {{/tb_t11/cpu/pla[20]} -radix hexadecimal} {{/tb_t11/cpu/pla[19]} -radix hexadecimal} {{/tb_t11/cpu/pla[18]} -radix hexadecimal} {{/tb_t11/cpu/pla[17]} -radix hexadecimal} {{/tb_t11/cpu/pla[16]} -radix hexadecimal} {{/tb_t11/cpu/pla[15]} -radix hexadecimal} {{/tb_t11/cpu/pla[14]} -radix hexadecimal} {{/tb_t11/cpu/pla[13]} -radix hexadecimal} {{/tb_t11/cpu/pla[12]} -radix hexadecimal} {{/tb_t11/cpu/pla[11]} -radix hexadecimal} {{/tb_t11/cpu/pla[10]} -radix hexadecimal} {{/tb_t11/cpu/pla[9]} -radix hexadecimal} {{/tb_t11/cpu/pla[8]} -radix hexadecimal} {{/tb_t11/cpu/pla[7]} -radix hexadecimal} {{/tb_t11/cpu/pla[6]} -radix hexadecimal} {{/tb_t11/cpu/pla[5]} -radix hexadecimal} {{/tb_t11/cpu/pla[4]} -radix hexadecimal} {{/tb_t11/cpu/pla[3]} -radix hexadecimal} {{/tb_t11/cpu/pla[2]} -radix hexadecimal} {{/tb_t11/cpu/pla[1]} -radix hexadecimal} {{/tb_t11/cpu/pla[0]} -radix hexadecimal}} -subitemconfig {{/tb_t11/cpu/pla[29]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[28]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[27]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[26]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[25]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[24]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[23]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[22]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[21]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[20]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[19]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[18]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[17]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[16]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[15]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[14]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[13]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[12]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[11]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[10]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[9]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[8]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[7]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[6]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[5]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[4]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[3]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[2]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[1]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pla[0]} {-height 15 -radix hexadecimal}} /tb_t11/cpu/pla
add wave -noupdate -group plm -label plm -radix hexadecimal -childformat {{{/tb_t11/cpu/plm[29]} -radix hexadecimal} {{/tb_t11/cpu/plm[28]} -radix hexadecimal} {{/tb_t11/cpu/plm[27]} -radix hexadecimal} {{/tb_t11/cpu/plm[26]} -radix hexadecimal} {{/tb_t11/cpu/plm[25]} -radix hexadecimal} {{/tb_t11/cpu/plm[24]} -radix hexadecimal} {{/tb_t11/cpu/plm[23]} -radix hexadecimal} {{/tb_t11/cpu/plm[22]} -radix hexadecimal} {{/tb_t11/cpu/plm[21]} -radix hexadecimal} {{/tb_t11/cpu/plm[20]} -radix hexadecimal} {{/tb_t11/cpu/plm[19]} -radix hexadecimal} {{/tb_t11/cpu/plm[18]} -radix hexadecimal} {{/tb_t11/cpu/plm[17]} -radix hexadecimal} {{/tb_t11/cpu/plm[16]} -radix hexadecimal} {{/tb_t11/cpu/plm[15]} -radix hexadecimal} {{/tb_t11/cpu/plm[14]} -radix hexadecimal} {{/tb_t11/cpu/plm[13]} -radix hexadecimal} {{/tb_t11/cpu/plm[12]} -radix hexadecimal} {{/tb_t11/cpu/plm[11]} -radix hexadecimal} {{/tb_t11/cpu/plm[10]} -radix hexadecimal} {{/tb_t11/cpu/plm[9]} -radix hexadecimal} {{/tb_t11/cpu/plm[8]} -radix hexadecimal} {{/tb_t11/cpu/plm[7]} -radix hexadecimal} {{/tb_t11/cpu/plm[6]} -radix hexadecimal} {{/tb_t11/cpu/plm[5]} -radix hexadecimal} {{/tb_t11/cpu/plm[4]} -radix hexadecimal} {{/tb_t11/cpu/plm[3]} -radix hexadecimal} {{/tb_t11/cpu/plm[2]} -radix hexadecimal} {{/tb_t11/cpu/plm[1]} -radix hexadecimal} {{/tb_t11/cpu/plm[0]} -radix hexadecimal}} -subitemconfig {{/tb_t11/cpu/plm[29]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[28]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[27]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[26]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[25]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[24]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[23]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[22]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[21]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[20]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[19]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[18]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[17]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[16]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[15]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[14]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[13]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[12]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[11]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[10]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[9]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[8]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[7]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[6]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[5]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[4]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[3]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[2]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[1]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/plm[0]} {-height 15 -radix hexadecimal}} /tb_t11/cpu/plm
add wave -noupdate -group plm -label plm_cz /tb_t11/cpu/plm_cz
add wave -noupdate -group plm -label sna -radix hexadecimal -childformat {{{/tb_t11/cpu/sna[5]} -radix octal} {{/tb_t11/cpu/sna[4]} -radix octal} {{/tb_t11/cpu/sna[3]} -radix octal} {{/tb_t11/cpu/sna[2]} -radix octal} {{/tb_t11/cpu/sna[1]} -radix octal} {{/tb_t11/cpu/sna[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/sna[5]} {-height 15 -radix octal} {/tb_t11/cpu/sna[4]} {-height 15 -radix octal} {/tb_t11/cpu/sna[3]} {-height 15 -radix octal} {/tb_t11/cpu/sna[2]} {-height 15 -radix octal} {/tb_t11/cpu/sna[1]} {-height 15 -radix octal} {/tb_t11/cpu/sna[0]} {-height 15 -radix octal}} /tb_t11/cpu/sna
add wave -noupdate -group iop -label iop -radix hexadecimal -childformat {{{/tb_t11/cpu/iop[15]} -radix hexadecimal} {{/tb_t11/cpu/iop[14]} -radix hexadecimal} {{/tb_t11/cpu/iop[13]} -radix hexadecimal} {{/tb_t11/cpu/iop[12]} -radix hexadecimal} {{/tb_t11/cpu/iop[11]} -radix hexadecimal} {{/tb_t11/cpu/iop[10]} -radix hexadecimal} {{/tb_t11/cpu/iop[9]} -radix hexadecimal} {{/tb_t11/cpu/iop[8]} -radix hexadecimal} {{/tb_t11/cpu/iop[7]} -radix hexadecimal} {{/tb_t11/cpu/iop[6]} -radix hexadecimal} {{/tb_t11/cpu/iop[5]} -radix hexadecimal} {{/tb_t11/cpu/iop[4]} -radix hexadecimal} {{/tb_t11/cpu/iop[3]} -radix hexadecimal} {{/tb_t11/cpu/iop[2]} -radix hexadecimal} {{/tb_t11/cpu/iop[1]} -radix hexadecimal} {{/tb_t11/cpu/iop[0]} -radix hexadecimal}} -subitemconfig {{/tb_t11/cpu/iop[15]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[14]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[13]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[12]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[11]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[10]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[9]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[8]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[7]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[6]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[5]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[4]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[3]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[2]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[1]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/iop[0]} {-height 15 -radix hexadecimal}} /tb_t11/cpu/iop
add wave -noupdate -group iop -label op -radix hexadecimal -childformat {{{/tb_t11/cpu/op[6]} -radix hexadecimal} {{/tb_t11/cpu/op[5]} -radix hexadecimal} {{/tb_t11/cpu/op[4]} -radix hexadecimal} {{/tb_t11/cpu/op[3]} -radix hexadecimal} {{/tb_t11/cpu/op[2]} -radix hexadecimal} {{/tb_t11/cpu/op[1]} -radix hexadecimal} {{/tb_t11/cpu/op[0]} -radix hexadecimal}} -subitemconfig {{/tb_t11/cpu/op[6]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/op[5]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/op[4]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/op[3]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/op[2]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/op[1]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/op[0]} {-height 15 -radix hexadecimal}} /tb_t11/cpu/op
add wave -noupdate -group alu -label af -radix octal -childformat {{{/tb_t11/cpu/af[15]} -radix octal} {{/tb_t11/cpu/af[14]} -radix octal} {{/tb_t11/cpu/af[13]} -radix octal} {{/tb_t11/cpu/af[12]} -radix octal} {{/tb_t11/cpu/af[11]} -radix octal} {{/tb_t11/cpu/af[10]} -radix octal} {{/tb_t11/cpu/af[9]} -radix octal} {{/tb_t11/cpu/af[8]} -radix octal} {{/tb_t11/cpu/af[7]} -radix octal} {{/tb_t11/cpu/af[6]} -radix octal} {{/tb_t11/cpu/af[5]} -radix octal} {{/tb_t11/cpu/af[4]} -radix octal} {{/tb_t11/cpu/af[3]} -radix octal} {{/tb_t11/cpu/af[2]} -radix octal} {{/tb_t11/cpu/af[1]} -radix octal} {{/tb_t11/cpu/af[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/af[15]} {-height 15 -radix octal} {/tb_t11/cpu/af[14]} {-height 15 -radix octal} {/tb_t11/cpu/af[13]} {-height 15 -radix octal} {/tb_t11/cpu/af[12]} {-height 15 -radix octal} {/tb_t11/cpu/af[11]} {-height 15 -radix octal} {/tb_t11/cpu/af[10]} {-height 15 -radix octal} {/tb_t11/cpu/af[9]} {-height 15 -radix octal} {/tb_t11/cpu/af[8]} {-height 15 -radix octal} {/tb_t11/cpu/af[7]} {-height 15 -radix octal} {/tb_t11/cpu/af[6]} {-height 15 -radix octal} {/tb_t11/cpu/af[5]} {-height 15 -radix octal} {/tb_t11/cpu/af[4]} {-height 15 -radix octal} {/tb_t11/cpu/af[3]} {-height 15 -radix octal} {/tb_t11/cpu/af[2]} {-height 15 -radix octal} {/tb_t11/cpu/af[1]} {-height 15 -radix octal} {/tb_t11/cpu/af[0]} {-height 15 -radix octal}} /tb_t11/cpu/af
add wave -noupdate -group alu -label ac -radix octal -childformat {{{/tb_t11/cpu/ac[16]} -radix octal} {{/tb_t11/cpu/ac[15]} -radix octal} {{/tb_t11/cpu/ac[14]} -radix octal} {{/tb_t11/cpu/ac[13]} -radix octal} {{/tb_t11/cpu/ac[12]} -radix octal} {{/tb_t11/cpu/ac[11]} -radix octal} {{/tb_t11/cpu/ac[10]} -radix octal} {{/tb_t11/cpu/ac[9]} -radix octal} {{/tb_t11/cpu/ac[8]} -radix octal} {{/tb_t11/cpu/ac[7]} -radix octal} {{/tb_t11/cpu/ac[6]} -radix octal} {{/tb_t11/cpu/ac[5]} -radix octal} {{/tb_t11/cpu/ac[4]} -radix octal} {{/tb_t11/cpu/ac[3]} -radix octal} {{/tb_t11/cpu/ac[2]} -radix octal} {{/tb_t11/cpu/ac[1]} -radix octal} {{/tb_t11/cpu/ac[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/ac[16]} {-height 15 -radix octal} {/tb_t11/cpu/ac[15]} {-height 15 -radix octal} {/tb_t11/cpu/ac[14]} {-height 15 -radix octal} {/tb_t11/cpu/ac[13]} {-height 15 -radix octal} {/tb_t11/cpu/ac[12]} {-height 15 -radix octal} {/tb_t11/cpu/ac[11]} {-height 15 -radix octal} {/tb_t11/cpu/ac[10]} {-height 15 -radix octal} {/tb_t11/cpu/ac[9]} {-height 15 -radix octal} {/tb_t11/cpu/ac[8]} {-height 15 -radix octal} {/tb_t11/cpu/ac[7]} {-height 15 -radix octal} {/tb_t11/cpu/ac[6]} {-height 15 -radix octal} {/tb_t11/cpu/ac[5]} {-height 15 -radix octal} {/tb_t11/cpu/ac[4]} {-height 15 -radix octal} {/tb_t11/cpu/ac[3]} {-height 15 -radix octal} {/tb_t11/cpu/ac[2]} {-height 15 -radix octal} {/tb_t11/cpu/ac[1]} {-height 15 -radix octal} {/tb_t11/cpu/ac[0]} {-height 15 -radix octal}} /tb_t11/cpu/ac
add wave -noupdate -group alu -label ax -radix octal -childformat {{{/tb_t11/cpu/ax[15]} -radix octal} {{/tb_t11/cpu/ax[14]} -radix octal} {{/tb_t11/cpu/ax[13]} -radix octal} {{/tb_t11/cpu/ax[12]} -radix octal} {{/tb_t11/cpu/ax[11]} -radix octal} {{/tb_t11/cpu/ax[10]} -radix octal} {{/tb_t11/cpu/ax[9]} -radix octal} {{/tb_t11/cpu/ax[8]} -radix octal} {{/tb_t11/cpu/ax[7]} -radix octal} {{/tb_t11/cpu/ax[6]} -radix octal} {{/tb_t11/cpu/ax[5]} -radix octal} {{/tb_t11/cpu/ax[4]} -radix octal} {{/tb_t11/cpu/ax[3]} -radix octal} {{/tb_t11/cpu/ax[2]} -radix octal} {{/tb_t11/cpu/ax[1]} -radix octal} {{/tb_t11/cpu/ax[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/ax[15]} {-height 15 -radix octal} {/tb_t11/cpu/ax[14]} {-height 15 -radix octal} {/tb_t11/cpu/ax[13]} {-height 15 -radix octal} {/tb_t11/cpu/ax[12]} {-height 15 -radix octal} {/tb_t11/cpu/ax[11]} {-height 15 -radix octal} {/tb_t11/cpu/ax[10]} {-height 15 -radix octal} {/tb_t11/cpu/ax[9]} {-height 15 -radix octal} {/tb_t11/cpu/ax[8]} {-height 15 -radix octal} {/tb_t11/cpu/ax[7]} {-height 15 -radix octal} {/tb_t11/cpu/ax[6]} {-height 15 -radix octal} {/tb_t11/cpu/ax[5]} {-height 15 -radix octal} {/tb_t11/cpu/ax[4]} {-height 15 -radix octal} {/tb_t11/cpu/ax[3]} {-height 15 -radix octal} {/tb_t11/cpu/ax[2]} {-height 15 -radix octal} {/tb_t11/cpu/ax[1]} {-height 15 -radix octal} {/tb_t11/cpu/ax[0]} {-height 15 -radix octal}} /tb_t11/cpu/ax
add wave -noupdate -group alu -group x -label x -radix octal -childformat {{{/tb_t11/cpu/x[15]} -radix octal} {{/tb_t11/cpu/x[14]} -radix octal} {{/tb_t11/cpu/x[13]} -radix octal} {{/tb_t11/cpu/x[12]} -radix octal} {{/tb_t11/cpu/x[11]} -radix octal} {{/tb_t11/cpu/x[10]} -radix octal} {{/tb_t11/cpu/x[9]} -radix octal} {{/tb_t11/cpu/x[8]} -radix octal} {{/tb_t11/cpu/x[7]} -radix octal} {{/tb_t11/cpu/x[6]} -radix octal} {{/tb_t11/cpu/x[5]} -radix octal} {{/tb_t11/cpu/x[4]} -radix octal} {{/tb_t11/cpu/x[3]} -radix octal} {{/tb_t11/cpu/x[2]} -radix octal} {{/tb_t11/cpu/x[1]} -radix octal} {{/tb_t11/cpu/x[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/x[15]} {-height 15 -radix octal} {/tb_t11/cpu/x[14]} {-height 15 -radix octal} {/tb_t11/cpu/x[13]} {-height 15 -radix octal} {/tb_t11/cpu/x[12]} {-height 15 -radix octal} {/tb_t11/cpu/x[11]} {-height 15 -radix octal} {/tb_t11/cpu/x[10]} {-height 15 -radix octal} {/tb_t11/cpu/x[9]} {-height 15 -radix octal} {/tb_t11/cpu/x[8]} {-height 15 -radix octal} {/tb_t11/cpu/x[7]} {-height 15 -radix octal} {/tb_t11/cpu/x[6]} {-height 15 -radix octal} {/tb_t11/cpu/x[5]} {-height 15 -radix octal} {/tb_t11/cpu/x[4]} {-height 15 -radix octal} {/tb_t11/cpu/x[3]} {-height 15 -radix octal} {/tb_t11/cpu/x[2]} {-height 15 -radix octal} {/tb_t11/cpu/x[1]} {-height 15 -radix octal} {/tb_t11/cpu/x[0]} {-height 15 -radix octal}} /tb_t11/cpu/x
add wave -noupdate -group alu -group x -label rx -radix octal /tb_t11/cpu/rx
add wave -noupdate -group alu -group x -label rx_ena /tb_t11/cpu/rx_ena
add wave -noupdate -group alu -group x -label halt_clr /tb_t11/cpu/halt_clr
add wave -noupdate -group alu -group x -label aclo_clr /tb_t11/cpu/aclo_clr
add wave -noupdate -group alu -group y -label y -radix octal -childformat {{{/tb_t11/cpu/y[15]} -radix octal} {{/tb_t11/cpu/y[14]} -radix octal} {{/tb_t11/cpu/y[13]} -radix octal} {{/tb_t11/cpu/y[12]} -radix octal} {{/tb_t11/cpu/y[11]} -radix octal} {{/tb_t11/cpu/y[10]} -radix octal} {{/tb_t11/cpu/y[9]} -radix octal} {{/tb_t11/cpu/y[8]} -radix octal} {{/tb_t11/cpu/y[7]} -radix octal} {{/tb_t11/cpu/y[6]} -radix octal} {{/tb_t11/cpu/y[5]} -radix octal} {{/tb_t11/cpu/y[4]} -radix octal} {{/tb_t11/cpu/y[3]} -radix octal} {{/tb_t11/cpu/y[2]} -radix octal} {{/tb_t11/cpu/y[1]} -radix octal} {{/tb_t11/cpu/y[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/y[15]} {-height 15 -radix octal} {/tb_t11/cpu/y[14]} {-height 15 -radix octal} {/tb_t11/cpu/y[13]} {-height 15 -radix octal} {/tb_t11/cpu/y[12]} {-height 15 -radix octal} {/tb_t11/cpu/y[11]} {-height 15 -radix octal} {/tb_t11/cpu/y[10]} {-height 15 -radix octal} {/tb_t11/cpu/y[9]} {-height 15 -radix octal} {/tb_t11/cpu/y[8]} {-height 15 -radix octal} {/tb_t11/cpu/y[7]} {-height 15 -radix octal} {/tb_t11/cpu/y[6]} {-height 15 -radix octal} {/tb_t11/cpu/y[5]} {-height 15 -radix octal} {/tb_t11/cpu/y[4]} {-height 15 -radix octal} {/tb_t11/cpu/y[3]} {-height 15 -radix octal} {/tb_t11/cpu/y[2]} {-height 15 -radix octal} {/tb_t11/cpu/y[1]} {-height 15 -radix octal} {/tb_t11/cpu/y[0]} {-height 15 -radix octal}} /tb_t11/cpu/y
add wave -noupdate -group alu -group y -label ry -radix octal -childformat {{{/tb_t11/cpu/ry[15]} -radix octal} {{/tb_t11/cpu/ry[14]} -radix octal} {{/tb_t11/cpu/ry[13]} -radix octal} {{/tb_t11/cpu/ry[12]} -radix octal} {{/tb_t11/cpu/ry[11]} -radix octal} {{/tb_t11/cpu/ry[10]} -radix octal} {{/tb_t11/cpu/ry[9]} -radix octal} {{/tb_t11/cpu/ry[8]} -radix octal} {{/tb_t11/cpu/ry[7]} -radix octal} {{/tb_t11/cpu/ry[6]} -radix octal} {{/tb_t11/cpu/ry[5]} -radix octal} {{/tb_t11/cpu/ry[4]} -radix octal} {{/tb_t11/cpu/ry[3]} -radix octal} {{/tb_t11/cpu/ry[2]} -radix octal} {{/tb_t11/cpu/ry[1]} -radix octal} {{/tb_t11/cpu/ry[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/ry[15]} {-height 15 -radix octal} {/tb_t11/cpu/ry[14]} {-height 15 -radix octal} {/tb_t11/cpu/ry[13]} {-height 15 -radix octal} {/tb_t11/cpu/ry[12]} {-height 15 -radix octal} {/tb_t11/cpu/ry[11]} {-height 15 -radix octal} {/tb_t11/cpu/ry[10]} {-height 15 -radix octal} {/tb_t11/cpu/ry[9]} {-height 15 -radix octal} {/tb_t11/cpu/ry[8]} {-height 15 -radix octal} {/tb_t11/cpu/ry[7]} {-height 15 -radix octal} {/tb_t11/cpu/ry[6]} {-height 15 -radix octal} {/tb_t11/cpu/ry[5]} {-height 15 -radix octal} {/tb_t11/cpu/ry[4]} {-height 15 -radix octal} {/tb_t11/cpu/ry[3]} {-height 15 -radix octal} {/tb_t11/cpu/ry[2]} {-height 15 -radix octal} {/tb_t11/cpu/ry[1]} {-height 15 -radix octal} {/tb_t11/cpu/ry[0]} {-height 15 -radix octal}} /tb_t11/cpu/ry
add wave -noupdate -group alu -group y -label ry_enh /tb_t11/cpu/ry_enh
add wave -noupdate -group alu -group y -label ry_enl /tb_t11/cpu/ry_enl
add wave -noupdate -group alu -group y -label sext /tb_t11/cpu/sext
add wave -noupdate -group alu -group y -label immed /tb_t11/cpu/immed
add wave -noupdate -group alu -group y -label inr_ry /tb_t11/cpu/inr_ry
add wave -noupdate -group alu -group dx -label dx -radix octal -childformat {{{/tb_t11/cpu/dx[15]} -radix octal} {{/tb_t11/cpu/dx[14]} -radix octal} {{/tb_t11/cpu/dx[13]} -radix octal} {{/tb_t11/cpu/dx[12]} -radix octal} {{/tb_t11/cpu/dx[11]} -radix octal} {{/tb_t11/cpu/dx[10]} -radix octal} {{/tb_t11/cpu/dx[9]} -radix octal} {{/tb_t11/cpu/dx[8]} -radix octal} {{/tb_t11/cpu/dx[7]} -radix octal} {{/tb_t11/cpu/dx[6]} -radix octal} {{/tb_t11/cpu/dx[5]} -radix octal} {{/tb_t11/cpu/dx[4]} -radix octal} {{/tb_t11/cpu/dx[3]} -radix octal} {{/tb_t11/cpu/dx[2]} -radix octal} {{/tb_t11/cpu/dx[1]} -radix octal} {{/tb_t11/cpu/dx[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/dx[15]} {-height 15 -radix octal} {/tb_t11/cpu/dx[14]} {-height 15 -radix octal} {/tb_t11/cpu/dx[13]} {-height 15 -radix octal} {/tb_t11/cpu/dx[12]} {-height 15 -radix octal} {/tb_t11/cpu/dx[11]} {-height 15 -radix octal} {/tb_t11/cpu/dx[10]} {-height 15 -radix octal} {/tb_t11/cpu/dx[9]} {-height 15 -radix octal} {/tb_t11/cpu/dx[8]} {-height 15 -radix octal} {/tb_t11/cpu/dx[7]} {-height 15 -radix octal} {/tb_t11/cpu/dx[6]} {-height 15 -radix octal} {/tb_t11/cpu/dx[5]} {-height 15 -radix octal} {/tb_t11/cpu/dx[4]} {-height 15 -radix octal} {/tb_t11/cpu/dx[3]} {-height 15 -radix octal} {/tb_t11/cpu/dx[2]} {-height 15 -radix octal} {/tb_t11/cpu/dx[1]} {-height 15 -radix octal} {/tb_t11/cpu/dx[0]} {-height 15 -radix octal}} /tb_t11/cpu/dx
add wave -noupdate -group alu -group dx -label sx_swp /tb_t11/cpu/sx_swp
add wave -noupdate -group alu -group dx -label dx_da /tb_t11/cpu/dx_da
add wave -noupdate -group alu -group dx -label sx_da /tb_t11/cpu/sx_da
add wave -noupdate -group alu -group wx -label wx -radix octal -childformat {{{/tb_t11/cpu/wx[15]} -radix octal} {{/tb_t11/cpu/wx[14]} -radix octal} {{/tb_t11/cpu/wx[13]} -radix octal} {{/tb_t11/cpu/wx[12]} -radix octal} {{/tb_t11/cpu/wx[11]} -radix octal} {{/tb_t11/cpu/wx[10]} -radix octal} {{/tb_t11/cpu/wx[9]} -radix octal} {{/tb_t11/cpu/wx[8]} -radix octal} {{/tb_t11/cpu/wx[7]} -radix octal} {{/tb_t11/cpu/wx[6]} -radix octal} {{/tb_t11/cpu/wx[5]} -radix octal} {{/tb_t11/cpu/wx[4]} -radix octal} {{/tb_t11/cpu/wx[3]} -radix octal} {{/tb_t11/cpu/wx[2]} -radix octal} {{/tb_t11/cpu/wx[1]} -radix octal} {{/tb_t11/cpu/wx[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/wx[15]} {-height 15 -radix octal} {/tb_t11/cpu/wx[14]} {-height 15 -radix octal} {/tb_t11/cpu/wx[13]} {-height 15 -radix octal} {/tb_t11/cpu/wx[12]} {-height 15 -radix octal} {/tb_t11/cpu/wx[11]} {-height 15 -radix octal} {/tb_t11/cpu/wx[10]} {-height 15 -radix octal} {/tb_t11/cpu/wx[9]} {-height 15 -radix octal} {/tb_t11/cpu/wx[8]} {-height 15 -radix octal} {/tb_t11/cpu/wx[7]} {-height 15 -radix octal} {/tb_t11/cpu/wx[6]} {-height 15 -radix octal} {/tb_t11/cpu/wx[5]} {-height 15 -radix octal} {/tb_t11/cpu/wx[4]} {-height 15 -radix octal} {/tb_t11/cpu/wx[3]} {-height 15 -radix octal} {/tb_t11/cpu/wx[2]} {-height 15 -radix octal} {/tb_t11/cpu/wx[1]} {-height 15 -radix octal} {/tb_t11/cpu/wx[0]} {-height 15 -radix octal}} /tb_t11/cpu/wx
add wave -noupdate -group alu -group wx -label sx_wh /tb_t11/cpu/sx_wh
add wave -noupdate -group alu -group wx -label sx_wl /tb_t11/cpu/sx_wl
add wave -noupdate -group alu -group wx -label rs_wre /tb_t11/cpu/rs_wre
add wave -noupdate -group alu -group wx -label rx_ena /tb_t11/cpu/rx_ena
add wave -noupdate -group alu -group ctrl -label alu_x00 /tb_t11/cpu/alu_x00
add wave -noupdate -group alu -group ctrl -label alu_x01 /tb_t11/cpu/alu_x01
add wave -noupdate -group alu -group ctrl -label alu_x10 /tb_t11/cpu/alu_x10
add wave -noupdate -group alu -group ctrl -label alu_x11 /tb_t11/cpu/alu_x11
add wave -noupdate -group alu -group ctrl -label alu_y01 /tb_t11/cpu/alu_y01
add wave -noupdate -group alu -group ctrl -label alu_y10 /tb_t11/cpu/alu_y10
add wave -noupdate -group alu -group ctrl -label alu_y11 /tb_t11/cpu/alu_y11
add wave -noupdate -group alu -group ctrl -label alu_rs /tb_t11/cpu/alu_rs
add wave -noupdate -group alu -group ctrl -label fc0 /tb_t11/cpu/fc0
add wave -noupdate -group alu -group ctrl -label fc1 /tb_t11/cpu/fc1
add wave -noupdate -group alu -group ctrl -label fc2 /tb_t11/cpu/fc2
add wave -noupdate -group alu -group ctrl -label fc3 /tb_t11/cpu/fc3
add wave -noupdate -group alu -group ctrl -label fc4 /tb_t11/cpu/fc4
add wave -noupdate -group alu -group psw -label psw -radix octal /tb_t11/cpu/psw
add wave -noupdate -group alu -group psw -label psw_n -radix octal /tb_t11/cpu/psw_n
add wave -noupdate -group alu -group psw -label psw_z -radix octal /tb_t11/cpu/psw_z
add wave -noupdate -group alu -group psw -label psw_v -radix octal /tb_t11/cpu/psw_v
add wave -noupdate -group alu -group psw -label psw_c -radix octal /tb_t11/cpu/psw_c
add wave -noupdate -group alu -group psw -label psw_wc -radix octal /tb_t11/cpu/psw_wc
add wave -noupdate -group alu -group psw -label psw_wf -radix octal /tb_t11/cpu/psw_wf
add wave -noupdate -group alu -group psw -label cf_t /tb_t11/cpu/cf_t
add wave -noupdate -group alu -group psw -label vf_t /tb_t11/cpu/vf_t
add wave -noupdate -group alu -group psw -label alu_zf /tb_t11/cpu/alu_zf
add wave -noupdate -group alu -group psw -label alu_cf /tb_t11/cpu/alu_cf
add wave -noupdate -group alu -group psw -label alu_nf /tb_t11/cpu/alu_nf
add wave -noupdate -group alu -group psw -label alu_vf /tb_t11/cpu/alu_vf
add wave -noupdate -group alu -group psw -label af_byte /tb_t11/cpu/af_byte
add wave -noupdate -group alu -label ac_in /tb_t11/cpu/ac_in
add wave -noupdate -group alu -label ax_in /tb_t11/cpu/ax_in
add wave -noupdate -group reg -label R0 -radix octal {/tb_t11/cpu/r[0]}
add wave -noupdate -group reg -label R1 -radix octal {/tb_t11/cpu/r[1]}
add wave -noupdate -group reg -label R2 -radix octal {/tb_t11/cpu/r[2]}
add wave -noupdate -group reg -label R3 -radix octal {/tb_t11/cpu/r[3]}
add wave -noupdate -group reg -label R4 -radix octal {/tb_t11/cpu/r[4]}
add wave -noupdate -group reg -label R5 -radix octal {/tb_t11/cpu/r[5]}
add wave -noupdate -group reg -label R6 -radix octal {/tb_t11/cpu/r[6]}
add wave -noupdate -group reg -label R7 -radix octal {/tb_t11/cpu/r[7]}
add wave -noupdate -group reg -label R8 -radix octal {/tb_t11/cpu/r[8]}
add wave -noupdate -group reg -label R9 -radix octal {/tb_t11/cpu/r[9]}
add wave -noupdate -group reg -label R10 -radix octal {/tb_t11/cpu/r[10]}
add wave -noupdate -group reg -label psw -radix octal -childformat {{{/tb_t11/cpu/psw[7]} -radix octal} {{/tb_t11/cpu/psw[6]} -radix octal} {{/tb_t11/cpu/psw[5]} -radix octal} {{/tb_t11/cpu/psw[4]} -radix octal} {{/tb_t11/cpu/psw[3]} -radix octal} {{/tb_t11/cpu/psw[2]} -radix octal} {{/tb_t11/cpu/psw[1]} -radix octal} {{/tb_t11/cpu/psw[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/psw[7]} {-height 15 -radix octal} {/tb_t11/cpu/psw[6]} {-height 15 -radix octal} {/tb_t11/cpu/psw[5]} {-height 15 -radix octal} {/tb_t11/cpu/psw[4]} {-height 15 -radix octal} {/tb_t11/cpu/psw[3]} {-height 15 -radix octal} {/tb_t11/cpu/psw[2]} {-height 15 -radix octal} {/tb_t11/cpu/psw[1]} {-height 15 -radix octal} {/tb_t11/cpu/psw[0]} {-height 15 -radix octal}} /tb_t11/cpu/psw
add wave -noupdate -group reg -group sel -label rsel -radix hexadecimal -childformat {{{/tb_t11/cpu/rsel[7]} -radix octal} {{/tb_t11/cpu/rsel[6]} -radix octal} {{/tb_t11/cpu/rsel[5]} -radix octal} {{/tb_t11/cpu/rsel[4]} -radix octal} {{/tb_t11/cpu/rsel[3]} -radix octal} {{/tb_t11/cpu/rsel[2]} -radix octal} {{/tb_t11/cpu/rsel[1]} -radix octal} {{/tb_t11/cpu/rsel[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/rsel[7]} {-height 15 -radix octal} {/tb_t11/cpu/rsel[6]} {-height 15 -radix octal} {/tb_t11/cpu/rsel[5]} {-height 15 -radix octal} {/tb_t11/cpu/rsel[4]} {-height 15 -radix octal} {/tb_t11/cpu/rsel[3]} {-height 15 -radix octal} {/tb_t11/cpu/rsel[2]} {-height 15 -radix octal} {/tb_t11/cpu/rsel[1]} {-height 15 -radix octal} {/tb_t11/cpu/rsel[0]} {-height 15 -radix octal}} /tb_t11/cpu/rsel
add wave -noupdate -group reg -group sel -label rselx -radix hexadecimal -childformat {{{/tb_t11/cpu/rselx[11]} -radix hexadecimal} {{/tb_t11/cpu/rselx[10]} -radix hexadecimal} {{/tb_t11/cpu/rselx[9]} -radix hexadecimal} {{/tb_t11/cpu/rselx[8]} -radix hexadecimal} {{/tb_t11/cpu/rselx[7]} -radix hexadecimal} {{/tb_t11/cpu/rselx[6]} -radix hexadecimal} {{/tb_t11/cpu/rselx[5]} -radix hexadecimal} {{/tb_t11/cpu/rselx[4]} -radix hexadecimal} {{/tb_t11/cpu/rselx[3]} -radix hexadecimal} {{/tb_t11/cpu/rselx[2]} -radix hexadecimal} {{/tb_t11/cpu/rselx[1]} -radix hexadecimal} {{/tb_t11/cpu/rselx[0]} -radix hexadecimal}} -subitemconfig {{/tb_t11/cpu/rselx[11]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/rselx[10]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/rselx[9]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/rselx[8]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/rselx[7]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/rselx[6]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/rselx[5]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/rselx[4]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/rselx[3]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/rselx[2]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/rselx[1]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/rselx[0]} {-height 15 -radix hexadecimal}} /tb_t11/cpu/rselx
add wave -noupdate -group reg -group sel -label rsely -radix hexadecimal /tb_t11/cpu/rsely
add wave -noupdate -group reg -group sel -label rs_d02 /tb_t11/cpu/rs_d02
add wave -noupdate -group reg -group sel -label rs_d35 /tb_t11/cpu/rs_d35
add wave -noupdate -group reg -group sel -label rs_s02 /tb_t11/cpu/rs_s02
add wave -noupdate -group reg -group sel -label rs_s35 /tb_t11/cpu/rs_s35
add wave -noupdate -group bus -group dal -label dal -radix octal -childformat {{{/tb_t11/cpu/dal[15]} -radix octal} {{/tb_t11/cpu/dal[14]} -radix octal} {{/tb_t11/cpu/dal[13]} -radix octal} {{/tb_t11/cpu/dal[12]} -radix octal} {{/tb_t11/cpu/dal[11]} -radix octal} {{/tb_t11/cpu/dal[10]} -radix octal} {{/tb_t11/cpu/dal[9]} -radix octal} {{/tb_t11/cpu/dal[8]} -radix octal} {{/tb_t11/cpu/dal[7]} -radix octal} {{/tb_t11/cpu/dal[6]} -radix octal} {{/tb_t11/cpu/dal[5]} -radix octal} {{/tb_t11/cpu/dal[4]} -radix octal} {{/tb_t11/cpu/dal[3]} -radix octal} {{/tb_t11/cpu/dal[2]} -radix octal} {{/tb_t11/cpu/dal[1]} -radix octal} {{/tb_t11/cpu/dal[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/dal[15]} {-height 15 -radix octal} {/tb_t11/cpu/dal[14]} {-height 15 -radix octal} {/tb_t11/cpu/dal[13]} {-height 15 -radix octal} {/tb_t11/cpu/dal[12]} {-height 15 -radix octal} {/tb_t11/cpu/dal[11]} {-height 15 -radix octal} {/tb_t11/cpu/dal[10]} {-height 15 -radix octal} {/tb_t11/cpu/dal[9]} {-height 15 -radix octal} {/tb_t11/cpu/dal[8]} {-height 15 -radix octal} {/tb_t11/cpu/dal[7]} {-height 15 -radix octal} {/tb_t11/cpu/dal[6]} {-height 15 -radix octal} {/tb_t11/cpu/dal[5]} {-height 15 -radix octal} {/tb_t11/cpu/dal[4]} {-height 15 -radix octal} {/tb_t11/cpu/dal[3]} {-height 15 -radix octal} {/tb_t11/cpu/dal[2]} {-height 15 -radix octal} {/tb_t11/cpu/dal[1]} {-height 15 -radix octal} {/tb_t11/cpu/dal[0]} {-height 15 -radix octal}} /tb_t11/cpu/dal
add wave -noupdate -group bus -group dal -label da_sth /tb_t11/cpu/da_sth
add wave -noupdate -group bus -group dal -label da_sth /tb_t11/cpu/da_stl
add wave -noupdate -group bus -group dal -label da_rd /tb_t11/cpu/da_rd
add wave -noupdate -group bus -group dal -label da_rst /tb_t11/cpu/da_rst
add wave -noupdate -group bus -group dal -label da_s0 /tb_t11/cpu/da_s0
add wave -noupdate -group bus -group dal -label da_s1 /tb_t11/cpu/da_s1
add wave -noupdate -group bus -group dal -label da_s2 /tb_t11/cpu/da_s2
add wave -noupdate -group bus -group dal -label da_s3 /tb_t11/cpu/da_s3
add wave -noupdate -group bus -group dal -label da_s4 /tb_t11/cpu/da_s4
add wave -noupdate -group bus -group dal -label da_s5 /tb_t11/cpu/da_s5
add wave -noupdate -group bus -group ras -label ras /tb_t11/cpu/ras
add wave -noupdate -group bus -group ras -label ras_c0 /tb_t11/cpu/ras_c0
add wave -noupdate -group bus -group ras -label ras_s0 /tb_t11/cpu/ras_s0
add wave -noupdate -group bus -group ras -label ras_s1 /tb_t11/cpu/ras_s1
add wave -noupdate -group bus -group ras -label sa_hx /tb_t11/cpu/sa_hx
add wave -noupdate -group bus -group cas -label cas /tb_t11/cpu/cas
add wave -noupdate -group bus -group cas -label cas_c0 /tb_t11/cpu/cas_c0
add wave -noupdate -group bus -group cas -label cas_s0 /tb_t11/cpu/cas_s0
add wave -noupdate -group bus -group cas -label cas_s1 /tb_t11/cpu/cas_s1
add wave -noupdate -group bus -group pr -label pr /tb_t11/cpu/pr
add wave -noupdate -group bus -group pr -label pr_c0 /tb_t11/cpu/pr_c0
add wave -noupdate -group bus -group pr -label pr_s0 /tb_t11/cpu/pr_s0
add wave -noupdate -group bus -group pr -label pr_s1 /tb_t11/cpu/pr_s1
add wave -noupdate -group bus -group pr -label pi_lat /tb_t11/cpu/pi_lat
add wave -noupdate -group bus -group pr -label inrq /tb_t11/cpu/inrq
add wave -noupdate -group bus -group pr -label aclo /tb_t11/cpu/aclo
add wave -noupdate -group bus -group pr -label halt /tb_t11/cpu/halt
add wave -noupdate -group bus -group pr -label vec /tb_t11/cpu/vec
add wave -noupdate -group bus -group pr -label inr -radix hexadecimal /tb_t11/cpu/inr
add wave -noupdate -group bus -group ra -label ra_stb /tb_t11/cpu/ra_stb
add wave -noupdate -group bus -group ra -label ra0_clr /tb_t11/cpu/ra0_clr
add wave -noupdate -group bus -group bsta -label iordy /tb_t11/cpu/iordy
add wave -noupdate -group bus -group bsta -label sa_ah /tb_t11/cpu/sa_ah
add wave -noupdate -group ir -label ir -radix octal -childformat {{{/tb_t11/cpu/ir[15]} -radix octal} {{/tb_t11/cpu/ir[14]} -radix octal} {{/tb_t11/cpu/ir[13]} -radix octal} {{/tb_t11/cpu/ir[12]} -radix octal} {{/tb_t11/cpu/ir[11]} -radix octal} {{/tb_t11/cpu/ir[10]} -radix octal} {{/tb_t11/cpu/ir[9]} -radix octal} {{/tb_t11/cpu/ir[8]} -radix octal} {{/tb_t11/cpu/ir[7]} -radix octal} {{/tb_t11/cpu/ir[6]} -radix octal} {{/tb_t11/cpu/ir[5]} -radix octal} {{/tb_t11/cpu/ir[4]} -radix octal} {{/tb_t11/cpu/ir[3]} -radix octal} {{/tb_t11/cpu/ir[2]} -radix octal} {{/tb_t11/cpu/ir[1]} -radix octal} {{/tb_t11/cpu/ir[0]} -radix octal}} -subitemconfig {{/tb_t11/cpu/ir[15]} {-height 15 -radix octal} {/tb_t11/cpu/ir[14]} {-height 15 -radix octal} {/tb_t11/cpu/ir[13]} {-height 15 -radix octal} {/tb_t11/cpu/ir[12]} {-height 15 -radix octal} {/tb_t11/cpu/ir[11]} {-height 15 -radix octal} {/tb_t11/cpu/ir[10]} {-height 15 -radix octal} {/tb_t11/cpu/ir[9]} {-height 15 -radix octal} {/tb_t11/cpu/ir[8]} {-height 15 -radix octal} {/tb_t11/cpu/ir[7]} {-height 15 -radix octal} {/tb_t11/cpu/ir[6]} {-height 15 -radix octal} {/tb_t11/cpu/ir[5]} {-height 15 -radix octal} {/tb_t11/cpu/ir[4]} {-height 15 -radix octal} {/tb_t11/cpu/ir[3]} {-height 15 -radix octal} {/tb_t11/cpu/ir[2]} {-height 15 -radix octal} {/tb_t11/cpu/ir[1]} {-height 15 -radix octal} {/tb_t11/cpu/ir[0]} {-height 15 -radix octal}} /tb_t11/cpu/ir
add wave -noupdate -group ir -label ir_sth /tb_t11/cpu/ir_sth
add wave -noupdate -group ir -label ir_stl /tb_t11/cpu/ir_stl
add wave -noupdate -group ir -label mi -radix octal -childformat {{{/tb_t11/cpu/mi[15]} -radix octal} {{/tb_t11/cpu/mi[14]} -radix octal} {{/tb_t11/cpu/mi[13]} -radix octal} {{/tb_t11/cpu/mi[12]} -radix octal} {{/tb_t11/cpu/mi[11]} -radix octal} {{/tb_t11/cpu/mi[10]} -radix octal} {{/tb_t11/cpu/mi[9]} -radix octal} {{/tb_t11/cpu/mi[8]} -radix octal} {{/tb_t11/cpu/mi[7]} -radix octal} {{/tb_t11/cpu/mi[6]} -radix octal}} -subitemconfig {{/tb_t11/cpu/mi[15]} {-height 15 -radix octal} {/tb_t11/cpu/mi[14]} {-height 15 -radix octal} {/tb_t11/cpu/mi[13]} {-height 15 -radix octal} {/tb_t11/cpu/mi[12]} {-height 15 -radix octal} {/tb_t11/cpu/mi[11]} {-height 15 -radix octal} {/tb_t11/cpu/mi[10]} {-height 15 -radix octal} {/tb_t11/cpu/mi[9]} {-height 15 -radix octal} {/tb_t11/cpu/mi[8]} {-height 15 -radix octal} {/tb_t11/cpu/mi[7]} {-height 15 -radix octal} {/tb_t11/cpu/mi[6]} {-height 15 -radix octal}} /tb_t11/cpu/mi
add wave -noupdate -group ir -label mo_op /tb_t11/cpu/mi_op
add wave -noupdate -group ir -label mi_src /tb_t11/cpu/mi_src
add wave -noupdate -group ir -label mi_dst /tb_t11/cpu/mi_dst
add wave -noupdate -group ir -label mi_dns /tb_t11/cpu/mi_dns
add wave -noupdate -group ir -label mi12_t /tb_t11/cpu/mi12_t
add wave -noupdate -group ir -label id -radix hexadecimal /tb_t11/cpu/id
add wave -noupdate -group ir -label id_dns /tb_t11/cpu/id_dns
add wave -noupdate -group ir -label st_dns /tb_t11/cpu/st_dns
add wave -noupdate -group ir -label pdc -radix hexadecimal -childformat {{{/tb_t11/cpu/pdc[12]} -radix hexadecimal} {{/tb_t11/cpu/pdc[11]} -radix hexadecimal} {{/tb_t11/cpu/pdc[10]} -radix hexadecimal} {{/tb_t11/cpu/pdc[9]} -radix hexadecimal} {{/tb_t11/cpu/pdc[8]} -radix hexadecimal} {{/tb_t11/cpu/pdc[7]} -radix hexadecimal} {{/tb_t11/cpu/pdc[6]} -radix hexadecimal} {{/tb_t11/cpu/pdc[5]} -radix hexadecimal} {{/tb_t11/cpu/pdc[4]} -radix hexadecimal} {{/tb_t11/cpu/pdc[3]} -radix hexadecimal} {{/tb_t11/cpu/pdc[2]} -radix hexadecimal} {{/tb_t11/cpu/pdc[1]} -radix hexadecimal} {{/tb_t11/cpu/pdc[0]} -radix hexadecimal}} -subitemconfig {{/tb_t11/cpu/pdc[12]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[11]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[10]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[9]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[8]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[7]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[6]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[5]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[4]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[3]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[2]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[1]} {-height 15 -radix hexadecimal} {/tb_t11/cpu/pdc[0]} {-height 15 -radix hexadecimal}} /tb_t11/cpu/pdc
add wave -noupdate -group tty -label rx_ie /tb_t11/tty_rx_ie
add wave -noupdate -group tty -label tx_ie /tb_t11/tty_tx_ie
add wave -noupdate -group tty -label tx_rdy /tb_t11/tty_tx_rdy
add wave -noupdate -group tty -label rd /tb_t11/tty_rd
add wave -noupdate -group tty -label wb /tb_t11/tty_wb
add wave -noupdate -group tty -label sel /tb_t11/tty_sel
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {69379584 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 147
configure wave -valuecolwidth 59
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {412454396 ps} {481833980 ps}
