# This file is generated by Anlogic Timing Wizard. 24 07 2020

#Created Clock
create_clock -name {eg4_clock_24} -period 41.666 -waveform { 0.000 20.833 } [get_ports {eg4_clock_24}]

#Derive PLL Clocks
derive_pll_clocks -gen_basic_clock

#Set False Path
set_false_path  -through [get_nets {cpu/reset/key_long}]
set_false_path  -through [get_nets {cpu/reset/key_down}]
set_false_path  -through [get_nets {cpu/reset/pwr_event}]

