name: on_pr

on:
    pull_request:
        branches:
          - master

jobs:
  sim:
    name: Run verification
    runs-on: [self-hosted, modelsim]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      - name: Run VM1 simulation
        run: vm1/hdl/syn/sim/de0/run_vsim.sh

